### PR TITLE
#1600: Improvements to mass delete message

### LINKED ISSUE #1600: Improvements to mass delete message
### Preconditions (*)

1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. Upload 4 to 5 images in the Media Gallery

### Steps to reproduce (*)

1. Go to Content - Media Gallery
2. Click on Delete Images button
3. Select 3 images to delete
4. Click on delete selected button
5. Check the popup message in which number of images is present
6. Click on delete image button in the popup
7. Check the success message

### Expected result (*)

Number of image should also be present in the success message

### Actual result (*)

image

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will add the specific number of assets selected to be deleted during mass delete.
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration https://github.com/magento/adobe-stock-integration/issues/1600: Improvements to mass delete message

### Manual testing scenarios (*)

1. Go to **Content - Media Gallery**
2. Click on **Delete Images** button
3. Select 3 images to delete
4. Click on **delete selected** button
5. Check the popup message in which number of images is present
6. Click on delete image button in the popup
7. The success message should show the specific number of images deleted.

### CODE REVIEW

**Comment by joweecaquicla** [comment]
@magento run all tests

File: MediaGalleryUi/Controller/Adminhtml/Image/Delete.php [hunk 1]
```diff
@@ -102,9 +102,9 @@ public function execute()
             $this->deleteImage->execute($assets);
             $responseCode = self::HTTP_OK;
             if (count($imageIds) === 1) {
-                $message = sprintf('The asset "%s" has been successfully deleted', current($assets)->getTitle());
+                $message = sprintf('The asset "%s" has been successfully deleted.', current($assets)->getTitle());
```
Comment (sivaschenko) [inline MediaGalleryUi/Controller/Adminhtml/Image/Delete.php]:
```suggestion
                $message = __('The asset "%title" has been successfully deleted.', ['title' => current($assets)->getTitle()]);
```

File: MediaGalleryUi/Controller/Adminhtml/Image/Delete.php [hunk 2]
```diff
@@ -102,9 +102,9 @@ public function execute()
...
             } else {
-                $message = 'Assets have been successfully deleted';
+                $message = sprintf('%s assets have been successfully deleted.', count($imageIds));
```
Comment (sivaschenko) [inline MediaGalleryUi/Controller/Adminhtml/Image/Delete.php]:
```suggestion
                $message = __('%count assets have been successfully deleted.', ['count' => count($imageIds)]);
```

File: MediaGalleryUi/Controller/Adminhtml/Image/Delete.php [hunk 3]
```diff
@@ -102,9 +102,9 @@ public function execute()
...
             }
             $responseContent = [
                 'success' => true,
```
Comment (sivaschenko) [inline MediaGalleryUi/Controller/Adminhtml/Image/Delete.php:120]: translation can be removed from $responseContent as message is already translated

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @joweecaquicla ! Let's also use the parametrized translation for these messages

**Comment by joweecaquicla** [comment]
@magento run all tests
