### PR TITLE
1626: Modified date and time changes to original after Media Gallery synchronization

### LINKED ISSUE #1626: Modified date and time changes to original after Media Gallery synchronization
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery, click on "three dots"
3. Select **Edit** 
4. Change the image _Title_ by typing a new, valid text. Click **Save**
5. Click on "three dots" again and select **View Details**
6. Verify that the _Modified_ date and time has changed
modified
7. Perform `php bin/magento media-gallery:sync`
8. Refresh the web page and View the image Details again
9. Verify the _Modified_ date and time

### Expected result (*)
The _Modified_ date and time did not change to the original. 

### Actual result (*)
The _Modified_ date and time is not saved and changed to original
modified_original

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will introduce the fix to the issue of modified date changing back to original value after Media Gallery synchronization.
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration https://github.com/magento/adobe-stock-integration/issues/1626: Modified date and time changes to original after Media Gallery synchronization

### Manual testing scenarios (*)

1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery, click on "three dots"
3. Select **Edit**
4. Change the image _Title_ by typing a new, valid text. Click **Save**
5. Click on "three dots" again and select **View Details**
6. Verify that the _Modified_ date and time has changed
7. Perform `php bin/magento media-gallery:sync`
8. Refresh the web page and View the image Details again
9. The modified date should not go back to its previous value.

### CODE REVIEW

**Comment by joweecaquicla** [comment]
@magento run all tests

File: MediaGallerySynchronization/Model/SynchronizeFiles.php [hunk 1]
```diff
@@ -85,7 +85,7 @@ public function execute(array $files): void
         foreach ($files as $file) {
             $path = $this->getFilePath($file);
             $time = $this->getFileModificationTime($file);
-            if (isset($assets[$path]) && $time === $assets[$path]) {
```
Comment (Nazar65) [inline MediaGallerySynchronization/Model/SynchronizeFiles.php]: Why you removing second part ?

Comment (Nazar65) [reply MediaGallerySynchronization/Model/SynchronizeFiles.php]: Basically to fix this issue we need to write new modified time to the metadata when we editing the file.

**Review by Nazar65 — CHANGES_REQUESTED** [review]

File: MediaGallerySynchronization/Model/SynchronizeFiles.php (hunk 1 above)
Comment (Nazar65) [reply MediaGallerySynchronization/Model/SynchronizeFiles.php]: ` if (isset($assets[$path]) && $time === $assets[$path]) {`
This part is responsible to synchronize files that were modified since last execution time, so when we editing file we must change the modified date in metadata as well.

**Comment by joweecaquicla** [comment]
@magento run all tests

**Comment by joweecaquicla** [comment]
After updating my branch, I was not able to replicate the issue but encountered a different one which is somehow related to this issue. When following the steps to reproduce, what happens after running `php bin/magento media-gallery:sync` is that the created at date follows the value of the modified date.

**Review by sivaschenko — APPROVED** [review]

**Review by chalov-anton — CHANGES_REQUESTED** [review]
:x: QA Failed

I have saved a new image Preview from Adobe Stock.
Edited the image Description.
Performed `php bin/magento media-gallery:sync`

Result:
_In Synchronize.php line 83:
  Failed to execute the following synchronizers: media_gallery_asset_synchronizer_
failed_to_execute_asset_syncronizer

Note:
The synchronization pass without any errors if delete the newly added image

**Comment by chalov-anton** [comment]
@joweecaquicla It seems like the issue is not in your PR. It is also reproducible on 2.0-develop.

**Comment by joweecaquicla** [comment]
> @joweecaquicla It seems like the issue is not in your PR. It is also reproducible on 2.0-develop.

@chalov-anton  Yes, I only encountered this issue when I pulled the updates from 2.0-develop.

**Comment by chalov-anton** [comment]
@joweecaquicla I'll move this PR back to _Acceptance Testing_

**Comment by sivaschenko** [comment]
@chalov-anton the add metadata fix has been merged (https://github.com/magento/adobe-stock-integration/pull/1668), please retest the PR

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

The modified date and time was not restored to original after `media-gallery:sync`
mod
