### PR TITLE
#1581: Add "Edit" button to Image Details page

### LINKED ISSUE #1581: Add "Edit" button to Image Details page
### Description
Editing image is only available from _"three dots" - Edit_. 
edit
According to the [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/162f3177-f504-454f-82e2-f5a8f89f92e4/), the Editing should be available from _Image Details_ page

### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select **View Details**
4. Verify if **Edit** button is available

### Expected result (*)
**Edit** button is available

### Actual result (*)
no_edit_button

### PR DESCRIPTION
**Pull request by jmonteros422**
### Description (*)

Add's Edit button with action handler in the Image Detail's Modal.

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1581: Add "Edit" button to Image Details page

### Manual testing scenarios (*)

1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select **View Details**
4. Verify if **Edit** button is available
5. Click Edit Button
6. Edit Details Panel should pop out

### CODE REVIEW

**Comment by jmonteros422** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js [hunk 1]
```diff
@@ -53,6 +53,16 @@ define([
             modalElement.modal('closeModal');
         },
 
+        /**
+         * Closes the image details and opens the image edit panel
+         */
+        editImageAction: function () {
+            var record = this.imageModel().getSelected().id;
+
+            this.closeModal();
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js]: Why do we need to close the modal here?

File: MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml [hunk 2]
```diff
@@ -71,6 +71,12 @@ use Magento\Backend\Block\Template;
                         "mediaGalleryImageDetailsName": "mediaGalleryImageDetails",
                         "imageModelName" : "standalone_media_gallery_listing.standalone_media_gallery_listing.media_gallery_columns.thumbnail_url",
                         "actionsList": [
+                            {
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml:75]: We have to add this button the `image-details.phtml` template file as well.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @jmonteros422, thanks for the pull request, it looks great! Please follow some comments below:

File: MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js (hunk 1 above)
Comment (jmonteros422) [reply MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js]: Hi @gabrieldagama, thank you for reviewing! This will close out the image view details modal before opening the edit details panel. If needed, I can sustain the view details modal then will figure out a way to trigger an update to its content after saving from the edit details panel.

Comment (gabrieldagama) [reply MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js]: Hi @jmonteros422 I think we should do that. Currently, if you change an image title using the edit feature, after saving, the user gets back to the grid, but if he opens the Image Details again, it has the old title. So we need to update that anyway. Let me know if it isn't clear! Thanks!

Comment (jmonteros422) [reply MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js]: @gabrieldagama, copy that! Thank you!

Comment (jmonteros422) [reply MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js]: Hi @gabrieldagama, just fyi, I have took some part of issue #1575 's resolution in order to achieve the update on the Image Details after saving from the Edit Panel. Thanks!

**Comment by gabrieldagama** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml [hunk 3]
```diff
@@ -47,6 +47,7 @@ use Magento\Backend\Block\Template;
                         "component": "Magento_MediaGalleryUi/js/image/image-details",
                         "imageDetailsUrl": "<?= $escaper->escapeJs($block->getData('imageDetailsUrl')); ?>",
                         "modalSelector": ".media-gallery-image-details-modal",
+                        "modalWindowSelector": ".media-gallery-image-details",
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml:50]: I think we can remove this one, it doesn't seem to be used.

File: MediaGalleryUi/view/adminhtml/web/js/image/image-details.js [hunk 4]
```diff
@@ -15,6 +15,7 @@ define([
         defaults: {
             template: 'Magento_MediaGalleryUi/image/image-details',
             modalSelector: '',
+            modalWindowSelector: '',
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-details.js:18]: I think we can remove this one, it doesn't seem to be used.

File: MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js [hunk 5]
```diff
@@ -54,6 +54,15 @@ define([
             modalElement.modal('closeModal');
         },
 
+        /**
+         * Closes the image details and opens the image edit panel
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js]:
```suggestion
         * Opens the image edit panel
```

File: MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js [hunk 6]
```diff
@@ -74,19 +83,21 @@ define([
         saveImageDetailsAction: function () {
             var saveDetailsUrl = this.mediaGalleryEditDetails().saveDetailsUrl,
                 modalElement = $(this.modalSelector),
-                dataForm = modalElement.find('#image-edit-details-form'),
-                imageId = this.imageModel().getSelected().id;
-
-            if (dataForm.validation('isValid')) {
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js:80]: I believe this validation has to stay, it probably came through when you pull the updates, let's make sure this still happens.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @jmonteros422 thanks for the updates! Please follow some minor comments, thanks.

File: MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml (hunk 3 above)
Comment (jmonteros422) [reply MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml:50]: Thanks for the review @gabrieldagama, currently using this one for 
MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js:99

**Comment by jmonteros422** [comment]
@magento run all tests

**Comment by jmonteros422** [comment]
@magento run Functional Tests B2B

File: MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js [hunk 7]
```diff
@@ -75,16 +84,21 @@ define([
...
                 modalElement = $(this.modalSelector),
                 dataForm = modalElement.find('#image-edit-details-form'),
-                imageId = this.imageModel().getSelected().id;
+                imageId = this.imageModel().getSelected().id,
+                imageDetails = this.mediaGalleryImageDetails();
 
             if (dataForm.validation('isValid')) {
                 saveDetails(
                     saveDetailsUrl,
-                    dataForm
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js]: We can leave the `dataForm` here instead, it is being used for validation and it is duplicating the code above.

File: MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml (hunk 3 above)
Comment (gabrieldagama) [reply MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml:50]: Hi @jmonteros422, you are right, that is being used on `image-actions.js`, but here we are injecting this value in `image-details.js`, that doesn't require that. The `image-actions.js` parameter is being passed through on this file line: 71.

File: MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js [hunk 8]
```diff
@@ -75,16 +84,21 @@ define([
...
+                    modalElement.find('#image-edit-details-form')
                 ).then(function () {
                     this.closeModal();
                     this.imageModel().reloadGrid();
-                    this.mediaGalleryImageDetails().removeCached(imageId);
+                    imageDetails.removeCached(imageId);
+
+                    if ($(imageDetails.modalWindowSelector).hasClass('_show')) {
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js]: It would be nice to wrap this into a function inside the `imageDetails` object, that will prevent code duplication if we need to re-use this method.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @jmonteros422, thanks for the updates! Please follow some minor comments below:

**Comment by jmonteros422** [comment]
@magento run all tests

**Review by gabrieldagama — DISMISSED** [review]
Approved, the failing tests are not related.

File: MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryViewDetailsEditTest.xml [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+-->
+
+<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
+    <test name="AdminMediaGalleryViewDetailsEditTest">
+        <annotations>
+            <features value="MediaGallery"/>
+            <useCaseId value="https://github.com/magento/adobe-stock-integration/issues/1581"/>
+            <title value="Editing an image from view details panel"/>
+            <stories value="[Issue #1581] Add Edit button to Image Details page"/>
+            <testCaseId value=""/>
```
Comment (sivaschenko) [inline MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryViewDetailsEditTest.xml]: I belive that would be the correct test case link
```suggestion
            <testCaseId value="https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/3961351"/>
```

File: MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryViewDetailsEditTest.xml [hunk 10]
```diff
@@ -0,0 +1,46 @@
...
+  */
+-->
+
+<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
+    <test name="AdminMediaGalleryViewDetailsEditTest">
+        <annotations>
+            <features value="MediaGallery"/>
+            <useCaseId value="https://github.com/magento/adobe-stock-integration/issues/1581"/>
+            <title value="Editing an image from view details panel"/>
+            <stories value="[Issue #1581] Add Edit button to Image Details page"/>
```
Comment (sivaschenko) [inline MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryViewDetailsEditTest.xml]:
```suggestion
            <stories value="[Story #44] User edits image meta data in Media Gallery"/>
```

File: MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewDetailsEditTest.xml [hunk 11]
```diff
@@ -0,0 +1,46 @@
...
+-->
+
+<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
+    <test name="AdminStandaloneMediaGalleryViewDetailsEditTest">
+        <annotations>
+            <features value="MediaGallery"/>
+            <useCaseId value="https://github.com/magento/adobe-stock-integration/issues/1581"/>
+            <title value="Editing an image from standalone view details panel"/>
+            <stories value="[Issue #1581] Add Edit button to standalone Image Details page"/>
+            <testCaseId value=""/>
```
Comment (sivaschenko) [inline MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewDetailsEditTest.xml]:
```suggestion
            <testCaseId value="https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/3961351"/>
```

File: MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewDetailsEditTest.xml [hunk 12]
```diff
@@ -0,0 +1,46 @@
...
+  */
+-->
+
+<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
+    <test name="AdminStandaloneMediaGalleryViewDetailsEditTest">
+        <annotations>
+            <features value="MediaGallery"/>
+            <useCaseId value="https://github.com/magento/adobe-stock-integration/issues/1581"/>
+            <title value="Editing an image from standalone view details panel"/>
+            <stories value="[Issue #1581] Add Edit button to standalone Image Details page"/>
```
Comment (sivaschenko) [inline MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewDetailsEditTest.xml]:
```suggestion
            <stories value="[Story #44] User edits image meta data in Media Gallery"/>
```

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the test coverage @jmonteros422 ! Please see the suggestions in comments

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Review by chalov-anton — CHANGES_REQUESTED** [review]
@jmonteros422 Great job, all works. 
But one note, can you please rename the **Edit Image** button into **Edit Details**
Edit_image

Like it is on the [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/162f3177-f504-454f-82e2-f5a8f89f92e4)
In my understanding, "Editing image" means editing the color, size etc...

**Comment by jmonteros422** [comment]
> @jmonteros422 Great job, all works.
> But one note, can you please rename the **Edit Image** button into **Edit Details**
> Edit_image
> 
> Like it is on the [UI Prototype](https://xd.adobe.com/view/0a8fc470-497b-4fd6-4043-62560c21d8db-7cbe/screen/162f3177-f504-454f-82e2-f5a8f89f92e4)
> In my understanding, "Editing image" means editing the color, size etc...

@chalov-anton , thank you for checking on that! Changes has been applied.

**Comment by jmonteros422** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by chalov-anton** [comment]
✔️ QA Passed 

Added a test on Cucumber Studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4974457
