### PR TITLE
#1589: Hitting Enter key on Edit Image page redirects the user to Magento Dashboard instead of Saving the image

### LINKED ISSUE #1589: Hitting "Enter" key on Edit Image page redirects the user to Magento Dashboard instead of Saving the image
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select **Edit**
4. Place the cursor into _Name_ field
5. Type any text
6. Hit Enter key from your keyboard

### Expected result (*)
The Edit Image window is closed, the file name is saved

### Actual result (*)
User is redirected to Magento Dashboard, the file name is not saved 
Peek 2020-07-09 17-04

### PR DESCRIPTION
**Pull request by yolouiese**
### Need to verify (*)
- If pressing Enter key closes edit image modal and saves the image details

### Description (*)
- Added event on data-bind attribute and created a function for Enter event key to prevent the page from reloading and to save image details

### Fixed Issues (if relevant)
1. Fixes magento/adobe-stock-integration#1589: Hitting Enter key on Edit Image page redirects the user to Magento Dashboard instead of Saving the image

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**
2. Select an image saved from Adobe Stock and click "three dots" in the bottom right
3. Select Edit
4. Place the cursor into Name or Description field
5. Type any text
6. Hit Enter key from your keyboard

### CODE REVIEW

**Comment by yolouiese** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js [hunk 1]
```diff
@@ -100,6 +100,25 @@ define([
...
             this.mediaGridMessages().scheduleCleanup();
+        },
+
+        /**
+         * Handle Enter key event to save image details
+         *
+         * @param {Object} data
+         * @param {jQuery.Event} event
+         */
+        handleEnterKey: function (data, event) {
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js:113]: I think we can use`Magento_Ui/js/lib/key-codes` instead of the 13, it will make it easier to understand. Do we need to return anything on this function? I think void would be cleaner and easier to understand.

Something like this:

```
        handleEnterKey: function (data, event) {
            var modalElement = $(this.modalSelector),
                key = keyCodes[event.keyCode];

            if (key === 'enterKey') {
                event.preventDefault();
                modalElement.find('.page-action-buttons button.save').click();
            }
        }
```

What do you think?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @yolouiese, thanks for the PR, it looks great! Please follow below a comment:

File: MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js (hunk 1 above)
Comment (yolouiese) [reply MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js:113]: Hi @gabrieldagama, thank you for reviewing my pull request. I just added the return for all keycodes other than the enter key since if there's no return, the user can no longer input anything in the input fields but I'll try your suggestion with the void. I'll just update my pull request. Thank you again.

Comment (yolouiese) [reply MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js:113]: Hi @gabrieldagama, I tried to work with a void but I had a problem with the input field where I can't type/input anything unless I add a return true. I updated my pull request with the requested changes. Thank you.

**Comment by yolouiese** [comment]
@magento run all tests

**Review by gabrieldagama — DISMISSED** [review]

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by yolouiese** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]
Approved, the failing tests are not related.

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA PAssed

Peek 2020-07-17 12-37
