### PR TITLE
#1515: Add keywords field to the edit image description slide panel

### LINKED ISSUE #1515: Add keywords field to the edit image description slide panel
Story: https://github.com/magento/adobe-stock-integration/issues/724

### Preconditions (*)
1. Install Magento 2.4-develop with Adobe Stock 2.0-develop
2. Enable Enhanced Media Gallery in the configuration
3. Have an image uploaded to the media gallery

### Steps to reproduce (*)
1. Login to admin panel
2. Open media gallery (I.e. Content -> Media Gallery menu)
3. Open context menu for the image by clicking on three dots next to the image in the grid
4. Select "Edit" option to open the Edit image details slide panel

### Expected result (*)
A popup appears with a warning message showing the content usage information for the selected assets

### Expected result (*)
Keywords filed is present in the slide panel

image

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will introduce the keywords field on the edit image details panel.

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration# https://github.com/magento/adobe-stock-integration/issues/1515: Add keywords field to the edit image description slide panel
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

File: MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js [hunk 1]
```diff
@@ -48,6 +50,7 @@ define([
                 getDetails(this.imageEditDetailsUrl, [imageId]).then(function (imageDetails) {
                     this.images[imageId] = imageDetails[imageId];
                     this.image(this.images[imageId]);
+                    this.mediaGalleryEditKeywordsDetails().getKeywordsOp(this.image().tags);
```
Comment (sivaschenko) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js]: Instead of setting keyword options - let's export the `image` from the image-edit component to the keywords-ui-select component

File: MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml [hunk 2]
```diff
@@ -53,6 +58,16 @@ use Magento\Backend\Block\Template;
                 }
             }
         },
+        "#media-gallery-image-edit-keywords-details": {
+            "Magento_Ui/js/core/app": {
+                "components": {
+                    "mediaGalleryEditKeywordsDetails": {
```
Comment (sivaschenko) [inline MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml]: I think it would be better to declare and initialize this component as a child to the edit details component. Please see `AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js` - `viewConfig`  for example

File: MediaGalleryUi/view/adminhtml/web/js/image/edit/keyword-ui-select.js [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+    'Magento_Ui/js/form/element/ui-select',
+    'jquery',
+    'underscore'
+], function (Select, $, _) {
+    'use strict';
+
+    return Select.extend({
+        defaults: {
+            template: 'Magento_MediaGalleryUi/image/edit/keyword-ui-select',
+            options: []
```
Comment (sivaschenko) [inline MediaGalleryUi/view/adminhtml/web/js/image/edit/keyword-ui-select.js]: `options` property is already declared and observed in the inherited component

File: MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js [hunk 4]
```diff
@@ -20,10 +21,42 @@ define([
...
             image: null,
             modules: {
-                mediaGridMessages: '${ $.mediaGridMessages }'
+                mediaGridMessages: '${ $.mediaGridMessages }',
+                select: '${ $.name }_select'
+            },
+            viewConfig: [
+                {
+                    component: 'Magento_MediaGalleryUi/js/image/edit/keyword-ui-select',
+                    name: '${ $.name }_select'
```
Comment (sivaschenko) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js]: I'd use a more specific name for the keywords field/select
```suggestion
                    name: '${ $.name }_keywords'
```

File: MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js [hunk 5]
```diff
@@ -49,6 +82,7 @@ define([
                     this.images[imageId] = imageDetails[imageId];
                     this.image(this.images[imageId]);
                     this.openEditImageDetailsModal();
+                    this.getKeywordsOp();
```
Comment (sivaschenko) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js]: To avoid this call, simply make sure the keywords component is rendering options based on the imported image

**Review by sivaschenko — COMMENTED** [review]
Thanks for the updates @joweecaquicla ! See my comments

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml [hunk 6]
```diff
@@ -48,12 +50,21 @@ use Magento\Backend\Block\Template;
...
-                        "mediaGridMessages": "standalone_media_gallery_listing.standalone_media_gallery_listing.messages"
+                        "mediaGridMessages": "standalone_media_gallery_listing.standalone_media_gallery_listing.messages",
+                        "viewConfig": [
+                            {
+                                "component": "Magento_Ui/js/form/element/ui-select",
+                                "name": "${ $.name }_keywords",
+                                "template": "ui/grid/filters/elements/ui-select",
+                                "disableLabel": true
+                            }
+                        ]
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml]: Do we need to declare this viewConfig here? Can't we just do it inside the JS file?

File: MediaGalleryUi/view/adminhtml/templates/image_edit_details.phtml [hunk 7]
```diff
@@ -48,12 +48,21 @@ use Magento\Backend\Block\Template;
...
-                        "mediaGridMessages": "standalone_media_gallery_listing.standalone_media_gallery_listing.messages"
+                        "mediaGridMessages": "standalone_media_gallery_listing.standalone_media_gallery_listing.messages",
+                        "viewConfig": [
+                            {
+                                "component": "Magento_Ui/js/form/element/ui-select",
+                                "name": "${ $.name }_keywords",
+                                "template": "ui/grid/filters/elements/ui-select",
+                                "disableLabel": true
+                            }
+                        ]
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/templates/image_edit_details.phtml]: Do we need to declare this viewConfig here? Can't we just do it inside the JS file?

File: MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js [hunk 8]
```diff
@@ -20,11 +22,102 @@ define([
...
+                {
+                    component: 'Magento_Ui/js/form/element/ui-select',
+                    name: '${ $.name }_keywords'
+                }
+            ],
+            exports: {
+                keywordOptions: '${ $.name }_keywords:options'
+            },
+            links: {
+                selectedKeywords: '${ $.name }_keywords:value'
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js]: I believe we should create a separate component like `ui-keywords` that extends `ui-select`, the way it is at the moment we have `image-edit` component changing linked properties and as consequence changing directly the `ui-select` state. By having separate component the component would have its own template and its own methods changing its own properties. What do you think?

**Review by gabrieldagama — COMMENTED** [review]
HI @joweecaquicla @sivaschenko, thanks for the PR, please follow below some comments.

File: MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js [hunk 9]
```diff
@@ -20,11 +22,102 @@ define([
...
+
+        /**
+         * Create an option object based on keyword string
+         *
+         * @param {String} keyword
+         * @returns {Object}
+         */
+        getOptionForKeyword: function(keyword) {
+            return {
+                'is_active': 1,
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js:90]:
```suggestion
                is_active: 1,
```

File: MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml (hunk 6 above)
Comment (sivaschenko) [reply MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml]: Thanks, generic component config was moved to the component defaults

File: MediaGalleryUi/view/adminhtml/templates/image_edit_details.phtml (hunk 7 above)
Comment (sivaschenko) [reply MediaGalleryUi/view/adminhtml/templates/image_edit_details.phtml]: Thanks, generic component config was moved to the component defaults

File: MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js (hunk 8 above)
Comment (sivaschenko) [reply MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js]: That's not actually keywords ui-select responsibility to change it's options/value. We may introduce a separate component for add new keyword field and button. However, in this case image-edit will still needs to be a proxy between ui-select and add-keyword components, so in my opinion that might increase the complexity. I'd postpone extracting additional components from `image-edit`

Comment (sivaschenko) [reply MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js]: As for adding the add keyword field to ui-select component approach - I wouldn't like to rewrite the ui-select component and template as that is a potential for conflicts on upgrades

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
Extracted task to use form ui component https://github.com/magento/adobe-stock-integration/issues/1690

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests
