### PR TITLE
1083: fix adobe stock asset save action

### LINKED ISSUE #1083: Adobe Stock Integration: not possible to save image.
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop
Internet Explorer 11 or Microsoft Edge 44...

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Disable Enhanced Media Gallery in Stores -> Configuration -> Advanced -> System 
3. Enable Adobe Stock Integration in Stores -> Configuration -> Advanced -> System 

### Steps to reproduce (*)
1. Open a media grid
2. Press Search Adobe Stock
3. Select image
4. Press Save preview
5. An error occurred and shown at the selected image above the Save preview button

### Expected result (*)
Image successfully saved to the adobe_stock_asset, media_gallery_asset_grid

### Actual result (*)
An error occurred, image not saved in the data storage: adobe_stock_asset, media_gallery_asset_grid

### PR DESCRIPTION
**Pull request by coderimus**
### Description (*)
Fix for the save image preview or licensed image related to the #1083 
The problem was in the size parameter which is not a media asset part but required for the media gallery grid table.

### Fixed Issues (if relevant)
#1083 

### Manual testing scenarios (*)
Use steps to reproduce from the #1083

### CODE REVIEW

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @coderimus ! 

I think it would be better to update 
 - `\Magento\MediaGalleryUi\Model\AssetIndexer`
- `\Magento\AdobeStockImage\Model\SaveImage::execute`
to save the size in the Media Asset entity in the first place (rather than only setting the size for the grid).

What do you think?

**Comment by coderimus** [comment]
@sivaschenko I tried to change the `Magento\AdobeStockImage\Model\SaveImage::execute` at the beginning but faced with next:` \Magento\AdobeStockImage\Model\Extract\MediaGalleryAsset` converts search result to the `\Magento\MediaGalleryApi\Api\Data\AssetInterface` and exclude size because it is not a getter of a MediaGalleryAsset :( and we do not have size as a storage column.

If we would add the size parameter as a part of a MediaGallery asset everything will be ok and easy to automate. From the other point of view, this looks not required. We can encapsulate knowledge about the size in the scope of the media_gallery_grid.

So we have 2 ways, I think:
1. Update MediaGallery asset with the new property `size`
2. Use PR's provided implementation to manage size information at storing it to the `media_gallery_grid`

**Comment by sivaschenko** [comment]
@coderimus please update your Magento codebase:
https://github.com/magento/magento2/blob/89bc0786ca0d5897362e5d30d0189aee0a6606d7/app/code/Magento/MediaGalleryApi/Api/Data/AssetInterface.php#L73

**Comment by coderimus** [comment]
@sivaschenko I implemented requested changes and adjust unit tests. Functionality works.

I have a suggestion: maybe we can exclude this part from the SaveImage class https://github.com/magento/adobe-stock-integration/blob/e3628a866d4e3570bbaea3f2fc44ad97afc0d1f0/AdobeStockImage/Model/SaveImage.php#L143-L169

and put it into a new SaveImageFile class where we can process all save file-related functionality and return MediaGallery asset? This should fix the code mess static test: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/adobe-stock-integration/pull/1087/bbbcbd733449dbca99dd5314b49e423a/Statics/allure-report-b2b/index.html#suites/51d3ab4d5d77a0bc6a7ea344e9e7e6be/4afb21c8e4b4da9/

**Comment by coderimus** [comment]
@sivaschenko  I think there is no other way at the first look and I implemented SaveImage class refactoring. Decouple save an Adobe Stock image and file processes. Unit tests provided. Please, review implementation.

File: AdobeStockImage/Model/SaveImageFile.php [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+     * @param string $destinationPath
+     *
+     * @return int
+     * @throws CouldNotSaveException
+     * @throws AlreadyExistsException
+     * @throws CouldNotDeleteException
+     * @throws FileSystemException
+     * @throws NoSuchEntityException
+     */
+    public function execute(Document $document, string $url, string $destinationPath): int
```
Comment (sivaschenko) [inline AdobeStockImage/Model/SaveImageFile.php]: Let's bread down this into two classes: `SaveImageFile` (lines 96-103) and `SaveMediaGalleryAsset` (lines 105-124)

File: AdobeStockImage/Model/SaveImageFile.php [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+        /* If the asset has been already saved, delete the previous version */
+        if (null !== $pathAttribute && $pathValue) {
+            $this->storageDelete->execute($pathValue);
+        }
+
+        $path = $this->storageSave->execute($url, $destinationPath);
+
+        $mediaDirectory = $this->fileSystem->getDirectoryRead(DirectoryList::MEDIA);
+        $absolutePath = $mediaDirectory->getAbsolutePath($path);
+        $fileSize = $mediaDirectory->stat($absolutePath)['size'];
```
Comment (sivaschenko) [inline AdobeStockImage/Model/SaveImageFile.php]: Please extract the size retrieval to a private function

File: AdobeStockImage/Model/SaveImage.php [hunk 3]
```diff
@@ -7,64 +7,28 @@
...
 use Magento\Framework\Exception\NoSuchEntityException;
-use Magento\MediaGalleryApi\Model\Asset\Command\GetByIdInterface;
-use Magento\MediaGalleryApi\Model\Asset\Command\SaveInterface;
 use Magento\MediaGalleryApi\Model\Keyword\Command\SaveAssetKeywordsInterface;
 
 /**
- * Test saving Adobe Stock Image to filesystem and database
+ * Save an image provided with the adobe Stock integration.
  */
 class SaveImage implements SaveImageInterface
```
Comment (sivaschenko) [inline AdobeStockImage/Model/SaveImage.php:27]: I like the refactoring!

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @coderimus thanks for the pull request! Please see my review comments

**Comment by coderimus** [comment]
@sivaschenko the final change made in the scope of the PR main goal and general improvements. Please, review.

File: AdobeStockImage/Model/SaveImageFile.php [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+        $pathAttribute = $document->getCustomAttribute('path');
+        $pathValue = $pathAttribute->getValue();
+        /* If the asset has been already saved, delete the previous version */
+        if (null !== $pathAttribute && $pathValue) {
+            $this->storageDelete->execute($pathValue);
+        }
+
+        $path = $this->storageSave->execute($url, $destinationPath);
+
+        return $path;
```
Comment (lenaorobei) [inline AdobeStockImage/Model/SaveImageFile.php]: `SaveImage` sounds like a command and should not return anything.

Comment (coderimus) [reply AdobeStockImage/Model/SaveImageFile.php]: @lenaorobei What about next change `SaveImageFileProcessor`? If ok, I will also change `SaveMediaGalleryAsset` to `SaveMediaGalleryAssetProcessor`.

Comment (lenaorobei) [reply AdobeStockImage/Model/SaveImageFile.php:73]: As per CQRS principle method should do whether do something or return something. In case of `save` it should return `void`.

Comment (lenaorobei) [reply AdobeStockImage/Model/SaveImageFile.php]: As per CQRS principle method should do whether do something or return something. In case of save it should return void.

File: AdobeStockImage/Model/SaveImage.php [hunk 5]
```diff
@@ -86,83 +51,64 @@ class SaveImage implements SaveImageInterface
...
      * @param string $destinationPath
      *
-     * @throws CouldNotSaveException
      * @throws AlreadyExistsException
      * @throws CouldNotDeleteException
+     * @throws CouldNotSaveException
      * @throws FileSystemException
      * @throws NoSuchEntityException
      */
     public function execute(Document $document, string $url, string $destinationPath): void
```
Comment (lenaorobei) [inline AdobeStockImage/Model/SaveImage.php:126]: I believe this method should  throw `CouldNotSaveException` exception only.

**Comment by coderimus** [comment]
@lenaorobei thank you for your review. I added some changes to the points you mentioned. Please, review when you have time.

**Comment by coderimus** [comment]
@sivaschenko I made adjustments according to review. Please, review.

File: AdobeStockImage/Model/GetSavedImageFilePath.php [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+use Magento\AdobeStockImage\Model\Storage\Save as StorageSave;
+use Magento\Framework\Api\Search\Document;
+use Magento\Framework\Exception\AlreadyExistsException;
+use Magento\Framework\Exception\CouldNotDeleteException;
+use Magento\Framework\Exception\FileSystemException;
+
+/**
+ * Save asset file and retrieve its path.
+ */
+class GetSavedImageFilePath implements GetSavedImageFilePathInterface
```
Comment (sivaschenko) [inline AdobeStockImage/Model/GetSavedImageFilePath.php]: The `Get` prefix in the name of this service is misleading. It actually deletes/saves the file. Let's change it to `SaveImageFile`

File: AdobeStockImage/Model/GetSavedImageFilePath.php [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+     * Save asset file to filesystem and return its path.
+     *
+     * @param Document $document
+     * @param string $url
+     * @param string $destinationPath
+     *
+     * @return string
+     * @throws AlreadyExistsException
+     * @throws CouldNotDeleteException
+     * @throws FileSystemException
```
Comment (sivaschenko) [inline AdobeStockImage/Model/GetSavedImageFilePath.php]: Let's throw only Could not save exception from this service for consistency

File: AdobeStockImage/Model/GetSavedImageFilePathInterface.php [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+     * @param Document $document
+     * @param string $url
+     * @param string $destinationPath
+     *
+     * @return string
+     * @throws CouldNotSaveException
+     * @throws AlreadyExistsException
+     * @throws CouldNotDeleteException
+     * @throws FileSystemException
+     * @throws NoSuchEntityException
```
Comment (sivaschenko) [inline AdobeStockImage/Model/GetSavedImageFilePathInterface.php]: phpdoc does not match with implementation, I'd use @inheritdoc in the implementation to avoid such discrepancy

File: AdobeStockImage/Model/GetSavedMediaGalleryAssetId.php [hunk 9]
```diff
@@ -0,0 +1,113 @@
...
+use Magento\Framework\Exception\NoSuchEntityException;
+use Magento\Framework\Filesystem;
+use Magento\AdobeStockAssetApi\Api\Data\AssetInterface;
+use Magento\MediaGalleryApi\Api\Data\AssetInterface as MediaGalleryAssetInterface;
+use Magento\MediaGalleryApi\Model\Asset\Command\SaveInterface;
+
+/**
+ * Process save action of the MediaGalleryAsset.
+ */
+class GetSavedMediaGalleryAssetId implements GetSavedMediaGalleryAssetIdInterface
```
Comment (sivaschenko) [inline AdobeStockImage/Model/GetSavedMediaGalleryAssetId.php]:
```suggestion
class SaveMediaGalleryAsset implements GetSavedMediaGalleryAssetIdInterface
```

File: AdobeStockImage/Model/GetSavedMediaGalleryAssetId.php [hunk 10]
```diff
@@ -0,0 +1,113 @@
...
+
+    /**
+     * Process saving MediaGalleryAsset based on the search document and destination path.
+     *
+     * @param Document $document
+     * @param string $destinationPath
+     *
+     * @return int
+     * @throws CouldNotSaveException
+     * @throws NoSuchEntityException
```
Comment (sivaschenko) [inline AdobeStockImage/Model/GetSavedMediaGalleryAssetId.php]: Let's throw only `CouldNotSaveException` (if the asset could not be loaded after we tried to save it - it's the result of the fact that we were not able to save the asset in the first place)

File: AdobeStockImage/Model/SaveImage.php [hunk 11]
```diff
@@ -7,64 +7,26 @@
...
-use Magento\Framework\Exception\NoSuchEntityException;
-use Magento\MediaGalleryApi\Model\Asset\Command\GetByIdInterface;
-use Magento\MediaGalleryApi\Model\Asset\Command\SaveInterface;
 use Magento\MediaGalleryApi\Model\Keyword\Command\SaveAssetKeywordsInterface;
+use Psr\Log\LoggerInterface;
 
 /**
- * Test saving Adobe Stock Image to filesystem and database
+ * Save an image provided with the adobe Stock integration.
+ * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
```
Comment (sivaschenko) [inline AdobeStockImage/Model/SaveImage.php:24]: I think SuppressWarnings can be removed as the coupling was reduced by reducing exception types variety

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @coderimus thanks for the updates, please take a look at my review comments

File: AdobeStockImage/Model/GetSavedImageFilePath.php (hunk 6 above)
Comment (coderimus) [reply AdobeStockImage/Model/GetSavedImageFilePath.php]: @sivaschenko I changed the `SaveImageFile` name to this one based on the discussion with @lenaorobei 
image

Comment (coderimus) [reply AdobeStockImage/Model/GetSavedImageFilePath.php]: My opinion that `SaveImageFile` good but also it returns the path of a file. As a variant, I used `RetrievePathFromImageSave`. What do you think about this?

Comment (sivaschenko) [reply AdobeStockImage/Model/GetSavedImageFilePath.php]: @lenaorobei I'd keep the return of the `SaveImageFile` in order to prevent discrepancies in case that path is adjusted by the storage. There is no way to retrieve the correct file path later in this case.

Please let me know what you think

Comment (sivaschenko) [reply AdobeStockImage/Model/GetSavedImageFilePath.php]: @coderimus Olena meant that the service should either save the file or provide the file path. This particular service is used to save the file, so the naming should not be changed. The question is whether to return the $path

Comment (coderimus) [reply AdobeStockImage/Model/GetSavedImageFilePath.php]: @sivaschenko thank you for details. I will check this. Also, as I understood, we need to return the name of the SaveMediaGalleryAsset, right? But in that case, we have to return id of the asset.

Comment (sivaschenko) [reply AdobeStockImage/Model/GetSavedImageFilePath.php]: If the service can be used each time I need to retrieve the path - "RetrievePath..." naming should be ok.

If the service is primarily used to save the file - it should be named accordingly.

`SaveImageFile` sounds good to me

Comment (sivaschenko) [reply AdobeStockImage/Model/GetSavedImageFilePath.php]: @coderimus after conversation with @lenaorobei we come to the next conclusions:
- The class name should be `SaveImageFile`
- The execute method should not return the path (use the argument destinationPath in clients instead) - return type `void`
- Update `\Magento\AdobeStockImage\Model\Storage\Save::execute` to make destinationPath a required parameter and chance the return type to `void`

File: AdobeStockImage/Model/SaveImage.php (hunk 11 above)
Comment (coderimus) [reply AdobeStockImage/Model/SaveImage.php:24]: Unfortunately, reducing a number of exceptions didn't help so I didn't remove SuppressWarnings.

File: AdobeStockImage/Model/Storage/Save.php [hunk 12]
```diff
@@ -52,7 +52,7 @@ public function __construct(
      * @throws AlreadyExistsException
      * @throws FileSystemException
      */
-    public function execute(string $imageUrl, string $destinationPath = '') : string
+    public function execute(string $imageUrl, string $destinationPath) : string
```
Comment (sivaschenko) [inline AdobeStockImage/Model/Storage/Save.php]:
```suggestion
    public function execute(string $imageUrl, string $destinationPath): void
```

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the updates @coderimus ! One final adjustment is required, please see my comment

File: AdobeStockImage/Model/Storage/Save.php (hunk 12 above)
Comment (coderimus) [reply AdobeStockImage/Model/Storage/Save.php]: @sivaschenko changes done :) Thank you.

**Review by sivaschenko — DISMISSED** [review]

File: AdobeStockImage/Model/SaveMediaGalleryAssetInterface.php [hunk 13]
```diff
@@ -0,0 +1,28 @@
...
+    /**
+     * Process saving MediaGalleryAsset based on the search document and destination path.
+     *
+     * @param Document $document
+     * @param string $destinationPath
+     *
+     * @return int
+     * @throws CouldNotSaveException
+     */
+    public function execute(Document $document, string $destinationPath): int;
```
Comment (lenaorobei) [inline AdobeStockImage/Model/SaveMediaGalleryAssetInterface.php]: Why the return type is `int`?

Comment (coderimus) [reply AdobeStockImage/Model/SaveMediaGalleryAssetInterface.php]: We return type int to process the next step of saving the Adobe Stock asset. We need it to save asset keywords and the adobe stock asset itself.

Comment (lenaorobei) [reply AdobeStockImage/Model/SaveMediaGalleryAssetInterface.php]: I believe we need to return `void`. The same like we did for `SaveImageFileInterface`.

Comment (coderimus) [reply AdobeStockImage/Model/SaveMediaGalleryAssetInterface.php]: @lenaorobei @sivaschenko I am going to provide changes in a hour.

Comment (coderimus) [reply AdobeStockImage/Model/SaveMediaGalleryAssetInterface.php]: @lenaorobei @sivaschenko I provided requested changes. Now `SaveImageFileInterface` also returns `void`. I used directly a command which gets media asset by a path.

**Comment by coderimus** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@coderimus could you please address PHPMD failure?

File: AdobeStockImage/Model/SaveImage.php [hunk 14]
```diff
@@ -88,6 +95,7 @@ public function __construct(
         DocumentToAsset $documentToAsset,
         SaveAssetKeywordsInterface $saveAssetKeywords,
         DocumentToKeywords $documentToKeywords,
+        SetLicensedInMediaGalleryGrid $setLicensedInMediaGalleryGrid,
```
Comment (lenaorobei) [inline AdobeStockImage/Model/SaveImage.php:98]: This dependency will be removed in https://github.com/magento/adobe-stock-integration/issues/1146

**Comment by lenaorobei** [comment]
@magento run Unit Tests

**Comment by lenaorobei** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by coderimus** [comment]
@lenaorobei @sivaschenko 
I checked failed MFTF test for the Adobe Stock Integration and find the reason why they failed. Currently, the Adobe stock integration returns the first image which doesn't have `More from this series` 
image
This leads to several issues: assertion failed when 4 images expected and click event also failed when it is looking for the "Show more" button. As a suggestion I provided the next adjustments: search images by the 'car' word :) https://github.com/magento/adobe-stock-integration/pull/1087/commits/2f48c34d84c0cddd36206d81400702bfb7b6b287#diff-83b62ecfd324289923a7b83edf6e8d0eR30-R32

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B

**Comment by lenaorobei** [comment]
@magento run Functional Tests B2B

File: AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php [hunk 15]
```diff
@@ -0,0 +1,195 @@
...
+            SaveMediaGalleryAsset::class,
+            [
+                'saveMediaAsset' =>  $this->saveMediaAssetMock,
+                'documentToMediaGalleryAsset' =>  $this->documentToMediaGalleryAssetMock,
+                'fileSystem' => $this->fileSystemMock
+            ]
+        );
+        $reflection = new \ReflectionClass(get_class($this->saveMediaAsset));
+        $reflectionMethod = $reflection->getMethod('calculateFileSize');
+        $reflectionMethod->setAccessible(true);
```
Comment (orlangur) [inline AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php:81]: As per conversation with @coderimus looked into this test implementation: it seems that refection was not used after all, but even if we would use it there is no need to call this method directly.

Please just call `execute` method in test as you already do and assert second parameter of `convert` call of media asset mock.
