### PR TITLE
[2.0.0-develop] Remove obsolete content after content synchronization

### LINKED ISSUE #1474: The "Used in" still displays that the image is used in a Product after the Product has been deleted
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)
1. Create a Product and add an image from Media Gallery
2. Go to Content - Media Gallery and View the Details of the image that was previously added to the Product
3. Verify that the Details display that the image is **Used In 1 Product**
4. Go to _Catalog - Products_ and **Delete** the previously created Product
5. Perform ``` bin/magento indexer:reindex, bin/magento media-content:sync, bin/magento cache:clean``` 
6. Go to Go to Content - Media Gallery and View the Details of the image that was previously Used

### Expected result (*)
The image is not Used in a product so it should not be displayed in Details

### Actual result (*)
The Details still display that the image is **Used In 1 Product**

### Note
Please also consider
- pages
- blocks
- categories

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1474: The "Used in" still displays that the image is used in a Product after the Product has been deleted
2. ...

### Manual testing scenarios (*)
1. Create a Product and add an image from Media Gallery
2. Go to Content - Media Gallery and View the Details of the image that was previously added to the Product
3. Verify that the Details display that the image is **Used In 1 Product**
4. Go to _Catalog - Products_ and **Delete** the previously created Product
5. Perform ``` bin/magento indexer:reindex, bin/magento media-content:sync, bin/magento cache:clean``` 
6. Go to Go to Content - Media Gallery and View the Details of the image that was previously Used

The image is not Used in a product so it should not be displayed in Details

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: MediaContentSynchronization/Model/RemoveObsoleteContentAsset.php [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+use Magento\MediaContentSynchronizationApi\Model\GetEntitiesInterface;
+use Magento\MediaContentSynchronization\Model\ResourceModel\GetOutdatedRelations;
+use Magento\MediaContentApi\Api\DeleteContentAssetLinksInterface;
+
+/**
+ * Remove obsolete content asset from deleted entities
+ */
+class RemoveObsoleteContentAsset
+{
+    private const MEDIA_CONTENT_ASSET_TABLE = 'media_content_asset';
```
Comment (lenaorobei) [inline MediaContentSynchronization/Model/RemoveObsoleteContentAsset.php]:
```suggestion
```

Comment (lenaorobei) [reply MediaContentSynchronization/Model/RemoveObsoleteContentAsset.php]: Duplicated in `GetOutdatedRelations`

File: MediaContentSynchronization/Model/ResourceModel/GetOutdatedRelations.php [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+                ['et' => $entityData->getEntityTable()],
+                'et.' . $entityData->getIdentifierField() . ' =  mca.entity_id ',
+                [$entityData->getIdentifierField(). ' AS entity_identifier']
+            );
+            $select->where('et.' . $entityData->getIdentifierField() . ' IS NULL');
+            $select->where('mca.entity_type = ?', $entityData->getEavEntityType() ?? $entityData->getEntityTable());
+            $assets = $connection->fetchAssoc($select);
+        } catch (\Exception $exception) {
+            $this->logger->critical($exception);
+            $message = __('Could not fetch media content links data');
```
Comment (lenaorobei) [inline MediaContentSynchronization/Model/ResourceModel/GetOutdatedRelations.php]: Would be nice to avoid one-time use variables.

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Please see minor review commants.

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by lenaorobei — DISMISSED** [review]

**Review by chalov-anton — CHANGES_REQUESTED** [review]
❌ QA Failed

Counts properly if you delete one entity. But if you delete more than one entity, the counter will remove only one.
For one synchronization, only one entity is removed

For example, 
1) the image is Used in 4 products.
2) user delete 2 products
3) user performs ```media-content:sync```

Actual Result: The View Details will display that the image is Used in 3 products
Expected Result: The View Details displays that the image is Used in 2 products

after another ```media-content:sync``` the View Details will display that the image is Used in 2 products

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
thank you @chalov-anton  could you please verify this issue now ?

**Comment by chalov-anton** [comment]
✔️ QA Passed

The previous concern is fixed
