### PR TITLE
#1688: Saved image from Adobe Stock is selected/highlighted, but the "Add Selected" button is not displayed

### LINKED ISSUE #1688: Saved image from Adobe Stock is selected/highlighted, but the "Add Selected" button is not displayed
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

1. Go to **Catalog - Categories**, 
2. Expand **Content**, click **Select from Gallery**
3. Click **Search Adobe Stock**
4. Save an Image Preview
5. Observe if the Image is selected/highlighted and if **Add Selected** button appeared

### Expected result (*)
The Image is selected/highlighted and **Add Selected** button appeared
selected_er

### Actual result (*)
The Image is selected/highlighted but the **Add Selected** button did not appear
selected_ar

### Note
- not reproducible with old Media Gallery
- user needs to deselect and select the image again

### PR DESCRIPTION
**Pull request by jmonteros422**
### Description (*)

This PR fixes issue related to #1688

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1688: Saved image from Adobe Stock is selected/highlighted, but the "Add Selected" button is not displayed

### Manual testing scenarios (*)

1. Go to **Catalog - Categories**, 
2. Expand **Content**, click **Select from Gallery**
3. Click **Search Adobe Stock**
4. Save an Image Preview
5. Observe if the Image is selected/highlighted and if **Add Selected** button appeared

### Expected result (*)
The Image is selected/highlighted and **Add Selected** button appeared
selected_er

### CODE REVIEW

**Comment by jmonteros422** [comment]
@magento run all tests

File: AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js [hunk 1]
```diff
@@ -243,7 +243,9 @@ define([
          * @param {Object} record
          */
         selectRecord: function (record) {
-            uiRegistry.get('name =' + this.mediaGallery).selected(record);
+            uiRegistry.get('name =' + this.mediaGallery)
+                .selected(record)
+                .toggleAddSelectedButton();
```
Comment (sivaschenko) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js]: I think it migth be better to use the `select` method that is responsible for handling that action
```suggestion
            uiRegistry.get('name =' + this.mediaGallery).select(record);
```

Comment (sivaschenko) [reply AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js]: Also can you please add `mediaGallery` property to defaults

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @jmonteros422 ! Please see my comments

**Comment by jmonteros422** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for updates @jmonteros422 ! The implementation look good! Can you please ensure this case is covered by an MFTF test (save preview image from adobe stock and add it to the content straight away)
@chalov-anton can you please provide the cucumber test case for MFTF test

**Comment by jmonteros422** [comment]
@magento run all tests

File: AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminMediaGalleryAddSelectedSavedPreviewActionGroup.xml [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+<!--
+ /**
+  * Copyright © Magento, Inc. All rights reserved.
+  * See COPYING.txt for license details.
+  */
+-->
+
+<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+              xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/actionGroupSchema.xsd">
+    <actionGroup name="AdminMediaGalleryAddSelectedSavedPreviewActionGroup">
```
Comment (sivaschenko) [inline AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminMediaGalleryAddSelectedSavedPreviewActionGroup.xml]: Please use `AdminSaveAdobeStockImagePreviewActionGroup` and `AdminMediaGalleryClickAddSelectedActionGroup` instead of this action group

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for updates @jmonteros422 ! Please see my comment

**Comment by jmonteros422** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed
The Image is selected/highlighted and Add Selected button appeared
Screenshot_72

Manual testing [scenario](https://studio.cucumber.io/projects/131313/test-plan/folders/1054245/scenarios/5068945)
