### PR TITLE
Polpulate asset metadata on uploading the image to magento && Populate media asset description when saving image from adobe stock

### LINKED ISSUE #1495: Populate media asset description when saving image from adobe stock
Story: https://github.com/magento/adobe-stock-integration/issues/724

### Preconditions (*)
1. Install Magento 2.4-develop with ASI 2.0-develop
2. Enable and Configure Adobe Stock Integration in the Stores -> Configuration -> System -> Adobe Stock Integration

### Steps to reproduce (*)
1. Login to Admin panel
2. Open the media gallery. I.e. from the Catalog -> Category -> Content fieldset -> Select image from gallery
3. Click "Search Adobe Stock" button
4. Click on any image to open the image preview panel
5. Click "License"/"Save Licensed" button
6. Confirm the image name in the popup

### Expected result (*)
The images information should be saved to the `media_gallery_asset` table. The `description` filed should be populated with the information provided from Adobe Stock

### Technical Details

Use the `\Magento\MediaGalleryMetadataApi\Api\ExtractMetadataInterface` to retrieve the metadata

### LINKED ISSUE #1497: Polpulate asset metadata on uploading the image to magento
Story: https://github.com/magento/adobe-stock-integration/issues/1183

### Preconditions (*)
1. Install Magento 2.4-develop with ASI 2.0-develop
2. Enable Enhanced Media Gallery

### Steps to reproduce (*)
1. Login to Admin panel
2. Open the media gallery. I.e. from the Catalog -> Category -> Content fieldset -> Select image from gallery
3. Click "Upload image" button and upload an image containing the title, description and keywords in the metadata

### Expected result (*)
The images information should be saved to the `media_gallery_asset` table. The `description`, `title` fields should be populated from the image metadata. the keywords should be saved for the image

### Testing

Should be checked for the next scenarios:
 - Uploading the image to the enhanced media gallery
 - Uploading the image to the old media gallery
 - Uploading the image to the category
 - Uploading the image to the Page builder
 - Runing `bin/magento media-gallery:sync` for images added manually to pub/media directory

### Technical Details

Use the `\Magento\MediaGalleryMetadataApi\Api\ExtractMetadataInterface` to retrieve the metadata
The changes should be applied to `\Magento\MediaGallerySynchronization\Model\CreateAssetFromFile::execute` method

### LINKED ISSUE #1627: Newly added Description is removed after Media Gallery synchronization
### Precondition (*)
1. Install Magento with Adobe Stock Integration
2. Enhanced Media Gallery is Enabled
3. A saved image Preview from Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select an image from Media Gallery, click on "three dots"
3. Select **Edit** 
4. Add image _Description_ by typing new, valid text. Click **Save**
5. Click on "three dots" again and select **View Details**
6. Verify that the _Description_ is added
desc
7. Perform `php bin/magento media-gallery:sync`
8. Refresh the web page and View the image Details again
9. Verify the _Description_ 

### Expected result (*)
The _Description_ is displayed

### Actual result (*)
The previously added _Description_ is removed
desc_rem

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1497: Polpulate asset metadata on uploading the image to magento
2. Fixes magento/adobe-stock-integration#1495: Populate media asset description when saving image from adobe stock
3. https://github.com/magento/adobe-stock-integration/issues/1627

### Manual testing scenarios (*)
Should be checked for the next scenarios:
 - Uploading the image to the enhanced media gallery
 - Uploading the image to the old media gallery
 - Uploading the image to the category
 - Uploading the image to the Page builder
 - Saving images from Adobe Stock
 - Runing `bin/magento media-gallery:sync` for images added manually to pub/media directory

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magenti run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: AdobeStockImage/Model/SaveMediaGalleryAsset.php [hunk 1]
```diff
@@ -79,13 +97,35 @@ public function execute(Document $document, string $destinationPath): void
                 'hash' => $this->hashImageContent($destinationPath)
             ];
 
+            $document = $this->setDescriptionFIeld($document, $destinationPath);
```
Comment (gabrieldagama) [inline AdobeStockImage/Model/SaveMediaGalleryAsset.php]:
```suggestion
            $document = $this->setDescriptionField($document, $destinationPath);
```

File: MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+
+        foreach ($metadata->getKeywords() as $keyword) {
+            $keywords[] = $this->keywordFactory->create(
+                [
+                    'keyword' => $keyword
+                ]
+            );
+        }
+        
+        $mediaAssetId = $this->getMediaGalleryAssetByPath->execute([$asset->getPath()])[0]->getId();
```
Comment (gabrieldagama) [inline MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php]: It seems that the asset loaded on line 84 is already the object with the Id that you need. See inside the `CreateAssetFromFile` method. I believe we can remove this one.

File: MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+        
+        $assetKeywords = $this->assetKeywordsFactory->create([
+            'assetId' => $mediaAssetId,
```
Comment (gabrieldagama) [inline MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php]:
```suggestion
            'assetId' => $asset->getId(),
```

File: MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+use Magento\MediaGalleryApi\Api\Data\AssetKeywordsInterfaceFactory;
+use Magento\MediaGalleryApi\Api\SaveAssetsKeywordsInterface;
+use Magento\MediaGalleryApi\Api\GetAssetsByPathsInterface;
+use Magento\MediaGallerySynchronization\Model\CreateAssetFromFile;
+use Magento\MediaGalleryApi\Api\Data\KeywordInterfaceFactory;
+
+/**
+ * Save image keywords metadata to the database
+ */
+class SaveImageKeywordsInformation
```
Comment (gabrieldagama) [inline MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php]:
```suggestion
class SaveImageAssetKeywords
```

File: MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+        $this->assetKeywordsFactory = $assetKeywordsFactory;
+        $this->getMediaGalleryAssetByPath = $getMediaGalleryAssetByPath;
+    }
+
+    /**
+     * Save image keywords metadata to the database.
+     *
+     * @param \SplFileInfo $file
+     */
+    public function execute(\SplFileInfo $file): void
```
Comment (gabrieldagama) [inline MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php]: I would actually recommend changing this signature to `execute(string $filePath, int $mediaAssetId)` the reason for that is:
- The `CreateAssetFromFile` that we are calling here also calls the `extractMetadata` to fetch the description from the file, but here we don't really need that to be done, we just need the Asset Id to save the keywords.
- The 2 places that we are actually using this class they already executed the `CreateAssetFromFile` and they actually have the asset object there, so it is easier for the client the pass the ID here.

What do you think?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @Nazar65, thanks for the pull request, it looks great! Please follow some comments below, let me know if you have any questions.

File: MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php (hunk 2 above)
Comment (Nazar65) [reply MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php]: but there is no id since this is new image

File: MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php (hunk 5 above)
Comment (Nazar65) [reply MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php]: agree :+1:

File: MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php (hunk 3 above)
Comment (Nazar65) [reply MediaGalleryIntegration/Model/SaveImageKeywordsInformation.php]: for the new file when we create asset asset id will be null

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Comment by chalov-anton** [comment]
✔️ QA Passed

Added a test scenario on Cucumber Studion - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4975591

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
need to refactor MFTF tests, as now test images contains metadata

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
@magento run Static Tests

File: MediaGalleryIntegration/Plugin/SaveImageInformation.php [hunk 6]
```diff
@@ -95,16 +69,15 @@ public function __construct(
...
             return $result;
         }
-        $this->saveAsset->execute([$this->createAssetFromFile->execute($file)]);
-        $this->storage->resizeFile($result['path'] . '/' . $result['file']);
+        $this->synchronizeFiles->execute([$path]);
 
         return $result;
     }
-
+
```
Comment (sivaschenko) [inline MediaGalleryIntegration/Plugin/SaveImageInformation.php]: please ensure there are no spaces on empty lines

File: MediaGalleryUi/composer.json [hunk 7]
```diff
@@ -10,7 +10,6 @@
         "magento/module-media-gallery-ui-api": "*",
         "magento/module-media-gallery-api": "*",
         "magento/module-media-gallery-synchronization": "*",
```
Comment (sivaschenko) [inline MediaGalleryUi/composer.json]: MediaGalleryUi should depend on MediaGallerySynchronizarionApi instead of MediaGallerySynchronizarion

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the PR @Nazar65 ! Please see my review comments

File: MediaGalleryUi/composer.json (hunk 7 above)
Comment (Nazar65) [reply MediaGalleryUi/composer.json]: ok

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

The locally uploaded jpeg image has Details, Description and Tags
