### PR TITLE
Open in Media Gallery button doesn't search for the image if the Title has been Edited

### LINKED ISSUE #1686: Open in Media Gallery button doesn't search for the image if the Title has been Edited
### Preconditions

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset

### Steps to reproduce (*)

1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Save an Image Preview
(_the image appeared in Media Gallery_)
3. Select the previously saved Unlicensed image
4. Click "three dots" and select **Edit**
5. Type a new **Title** and click **Save**
6. Click **Search Adobe Stock** 
_(the image preview is opened)_
7. Click **Open in Media Gallery**

### Expected result (*)
The new image title is used for search and the image is found

### Actual result (*)
The image title from Adobe Stock is used for Search, and as a result - the image is not found
Peek 2020-07-30 17-44

### PR DESCRIPTION
**Pull request by Nazar65**
### Related Pull Requests
https://github.com/magento/partners-magento2-infrastructure/pull/21

### Fixed Issues (if relevant)

2. Fixes magento/adobe-stock-integration#1686: Open in Media Gallery button doesn't search for the image if the Title has been Edited

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**, click **Search Adobe Stock**
2. Save an Image Preview
(_the image appeared in Media Gallery_)
3. Select the previously saved Unlicensed image
4. Click "three dots" and select **Edit**
5. Type a new **Title** and click **Save**
6. Click **Search Adobe Stock** 
_(the image preview is opened)_
7. Click **Open in Media Gallery**

The new image title is used for search and the image is found

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetDetails.php [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+use Magento\Backend\App\Action;
+use Magento\Framework\App\Action\HttpPostActionInterface;
+use Magento\Framework\Controller\Result\Json;
+use Magento\Framework\Controller\ResultFactory;
+use Psr\Log\LoggerInterface;
+
+/**
+ * Backend controller for retrieving asset information by adobeId
+ */
+class GetDetails extends Action implements HttpPostActionInterface
```
Comment (sivaschenko) [inline AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetDetails.php]: I think it's better to introduce the GetMediaGalleryAsset controller to retrieve media gallery asset by `adobe_id` to avoid double request.

File: AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetDetails.php [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+                ];
+                $resultJson->setHttpResponseCode(self::HTTP_BAD_REQUEST);
+                $resultJson->setData($responseContent);
+
+                return $resultJson;
+            }
+
+            $result = $this->getAssetById->execute([$adobeId]);
+            $responseCode = self::HTTP_OK;
+            $responseContent = $result[$adobeId]->getData();
```
Comment (sivaschenko) [inline AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetDetails.php]: Please avoid using methods that are not declared on interface

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @Nazar65 ! Please see my comments

File: AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetDetails.php (hunk 2 above)
Comment (Nazar65) [reply AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetDetails.php]: ok

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js [hunk 3]
```diff
@@ -137,20 +137,47 @@ define([
...
         },
 
+        /**
+         * Return adobe stock asset by adobe id
+         *
+         * @param {String} adobeId
+         */
+        getAssetDetails: function (adobeId) {
+            return $.ajax({
+                url: this.getAssetDetailsUrl,
```
Comment (sivaschenko) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js]:
```suggestion
                url: this.getMediaGalleryAsset,
```
Also please add the filed to defaults

File: AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetMediaGalleryAsset.php [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+                    'message' => __('Adobe id is required.'),
+                ];
+                $resultJson->setHttpResponseCode(self::HTTP_BAD_REQUEST);
+                $resultJson->setData($responseContent);
+
+                return $resultJson;
+            }
+
+            $mediaGalleryId = $this->getAssetById->execute([$adobeId])[$adobeId]->getMediaGalleryId();
+            $details = $this->getDetailsByAssetId->execute([$mediaGalleryId]);
```
Comment (sivaschenko) [inline AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetMediaGalleryAsset.php]: I don't think the media gallery asset details are required on this stage. I'd prefer to retrieve asset from `\Magento\MediaGalleryApi\Api\GetAssetsByIdsInterface` and use `\Magento\Framework\Reflection\DataObjectProcessor::buildOutputDataArray` to retrieve the data for response.

Please extract the logic from controller to a model

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for updates @Nazar65 ! Please see my comments

File: AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetMediaGalleryAsset.php (hunk 4 above)
Comment (Nazar65) [reply AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetMediaGalleryAsset.php]: ok

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: AdobeStockImageAdminUi/Model/Asset/GetMediaGalleryAssetByAdobeId.php [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+     * @throws LocalizedException
+     */
+    public function execute(int $adobeId): array
+    {
+        try {
+            $mediaGalleryId = $this->getAssetByAdobeId->execute([$adobeId])[$adobeId]->getMediaGalleryId();
+            $asset = $this->getMediaGalleryAssetsById->execute([$mediaGalleryId]);
+
+            return $this->objectProcessor->buildOutputDataArray(current($asset), AssetInterface::class);
+        } catch (\Exception $e) {
```
Comment (sivaschenko) [inline AdobeStockImageAdminUi/Model/Asset/GetMediaGalleryAssetByAdobeId.php]: I don't think exception handling is necessary here. The controller should take care of it

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for updates @Nazar65 ! Please check my comment

File: AdobeStockImageAdminUi/Model/Asset/GetMediaGalleryAssetByAdobeId.php (hunk 5 above)
Comment (Nazar65) [reply AdobeStockImageAdminUi/Model/Asset/GetMediaGalleryAssetByAdobeId.php]: ok

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Review by sivaschenko — CHANGES_REQUESTED** [review]
@Nazar65 thanks for updates! The implemenation looks good. Can you please create a related infra PR nd fix the static tests

**Review by sivaschenko — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

The new image title is used for search and the image is found
Peek 2020-08-11 14-39
Screenshot_74
