### PR TITLE
#1496: Add hash to asset on uploading the image to magento

### LINKED ISSUE #1496: Add hash to asset on uploading the image to magento
Story: https://github.com/magento/adobe-stock-integration/issues/1484

### Preconditions (*)
1. Install Magento 2.4-develop with ASI 2.0-develop
2. Enable Enhanced Media Gallery

### Steps to reproduce (*)
1. Login to Admin panel
2. Open the media gallery. I.e. from the Catalog -> Category -> Content fieldset -> Select image from gallery
3. Click "Upload image" button and upload an image

### Expected result (*)
The images information should be saved to the `media_gallery_asset` table. The `hash` filed should be populated with the `sha1` hash of the image content

### Testing

Should be checked for the next scenarios:
 - Uploading the image to the enhanced media gallery
 - Uploading the image to the old media gallery
 - Uploading the image to the category
 - Uploading the image to the Page builder
 - Runing `bin/magento media-gallery:sync` for images added manually to pub/media directory

### Technical Details

The changes should be applied to `\Magento\MediaGallerySynchronization\Model\CreateAssetFromFile::execute` method

### PR DESCRIPTION
**Pull request by joweecaquicla**
### Description (*)

This PR will implement the adding of hash to the asset on uploading the image to Magento.
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1496: Add hash to asset on uploading the image to magento
2. ...

### CODE REVIEW

**Comment by joweecaquicla** [comment]
@magento run all tests

File: MediaGallerySynchronization/Model/CreateAssetFromFile.php [hunk 1]
```diff
@@ -137,4 +145,20 @@ private function getMediaDirectory(): Read
...
+     * @param string $path
+     * @return string
+     * @throws FileSystemException
+     * @throws ValidatorException
+     */
+    private function getHashImageContent(string $path): string
+    {
+        $mediaDirectory = $this->filesystem->getDirectoryRead(DirectoryList::MEDIA);
+        $imageContent = $mediaDirectory->readFile($this->getRelativePath($path));
+        $hashedImageContent = sha1($imageContent);
```
Comment (sivaschenko) [inline MediaGallerySynchronization/Model/CreateAssetFromFile.php]: Could you please wrap the `sha1` hashing call to a new class to be able to reuse it.

`Magento/MediaGallerySynchronization/Model/GetContentHash` class implementing `Magento/MediaGallerySynchronizationApi/Model/GetContentHashInterface` with a single `public function execute(string $content): string` returning the hash.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks @joweecaquicla ! Please take a look at the review comment.

File: MediaGallerySynchronization/Model/CreateAssetFromFile.php (hunk 1 above)
Comment (lenaorobei) [reply MediaGallerySynchronization/Model/CreateAssetFromFile.php]: Why cannot we use `sha1_file` here? Another point I would consider is moving this "anti corruption layer" layer to framework.

Comment (joweecaquicla) [reply MediaGallerySynchronization/Model/CreateAssetFromFile.php]: @sivaschenko this is noted.
@lenaorobei I’ve looked up about `sha1` and `sha1_file` earlier and I think `sha1_file` should be used instead since we’re dealing with image files.

**Comment by joweecaquicla** [comment]
@magento run all tests

File: MediaGallerySynchronization/Model/FileEncryption/Sha1File.php [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
+declare(strict_types=1);
+
+namespace Magento\MediaGallerySynchronization\Model\FileEncryption;
+
+use Magento\MediaGallerySynchronizationApi\Model\FileEncryptionInterface;
+
+class Sha1File implements FileEncryptionInterface
```
Comment (sivaschenko) [inline MediaGallerySynchronization/Model/FileEncryption/Sha1File.php]: I don't think this additional class and interface are needed. It's enough to have only GetContentHash and GetContentHashInterface.

File: MediaGallerySynchronizationApi/Model/GetContentHashInterface.php [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+ */
+interface GetContentHashInterface
+{
+    /**
+     * Get hashed value of image content.
+     *
+     * @param string $filepath
+     * @return string
+     */
+    public function execute(string $filepath): string;
```
Comment (sivaschenko) [inline MediaGallerySynchronizationApi/Model/GetContentHashInterface.php]:
```suggestion
    public function execute(string $content): string;
```

It would be better to work with file content instead of the file (we wouldn't like to include file path/name in the hash) as it will not allow us to use this hash for duplicates detection

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the updates @joweecaquicla Please see my comments

**Comment by sivaschenko** [comment]
@joweecaquicla can you please cover `GetContentHashInterface` with the integration test.

The test cases for the integration test:
 - Have two files with the same content.
 - Get hashes from these two files using `GetContentHashInterface`
 - The hashes should be equal

File: MediaGallerySynchronizationApi/Model/GetContentHashInterface.php (hunk 3 above)
Comment (joweecaquicla) [reply MediaGallerySynchronizationApi/Model/GetContentHashInterface.php]: If we're gonna go with hashing the file content, then we'll go with `sha1()` instead of `sha1_file()` since the latter uses file path as a parameter instead of the entire file content.

**Comment by joweecaquicla** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Comment by sivaschenko** [comment]
Covered with integration tests, doesn't require manual testing

**Comment by joweecaquicla** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run Integration Tests

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

Test on Cucumber Studio - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/4942139
(Test State - _In Progress_)
