### PR TITLE
Set property when component initialized

### LINKED ISSUE #1356: "Uncaught TypeError: Cannot read property 'setActive' of undefined" appears in dev console if select a directory in Media Gallery and refresh the web page
The bug is not reproducible constantly. I'm able to reproduce in 2 times out of 5 on my machine

### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Have a folder created in Media Gallery

### Steps to reproduce (*)
1. Go to **Content - Media Gallery** click **Search Adobe Stock**
2. Select any folder from the folder tree
(Directory filter becomes active)
3. Refresh the web page
4. Observe the dev console 

### Expected result (*)
No error message in dev console 

### Actual result (*)
:x: _Uncaught TypeError: Cannot read property 'setActive' of undefined_ appears 
set_active_uncought type error

set_active_uncought type error

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1356: 
"Uncaught TypeError: Cannot read property 'setActive' of undefined" appears in dev console if select a directory in Media Gallery and refresh the web page
2. ...

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery** click **Search Adobe Stock**
2. Select any folder from the folder tree
(Directory filter becomes active)
3. Refresh the web page
4. Observe the dev console 

### Expected result (*)
No error message in dev console

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js [hunk 1]
```diff
@@ -71,6 +71,19 @@ define([
             }
         },
 
+        /**
+         * Wait for component to initialize
+         */
+        waitForComponent: function (callback, component) {
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: We already have a method that performs similar action on this component (waitForContainer), I would suggest we extract the if condition and define it as a parameter, rename the method to waitForCondition and use it for both approaches.

Something like this:
```
waitForCondition: function (condition, callback) {
            if (condition()) {
                setTimeout(function () {
                    this.waitForCondition(condition, callback);
                }.bind(this), 100);
            } else {
                callback();
            }
        },
```

And to call that method we would do:

```
            this.waitForCondition(function () {
                return $(this.directoryTreeSelector).length === 0
            }.bind(this), function () {
                this.getJsonTree();
                this.initEvents();
                this.checkChipFiltersState();
            }.bind(this));
```

**Review by gabrieldagama — COMMENTED** [review]
Hi @Nazar65, thanks for your pull request, follow below some suggestion, thank you!

File: MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js (hunk 1 above)
Comment (Nazar65) [reply MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: completely agree with you.

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@gabrieldagama thanks for you review, done :heavy_check_mark:

**Review by gabrieldagama — DISMISSED** [review]

**Comment by gabrieldagama** [comment]
Thanks @Nazar65, I've approved it. Failed tests are not related to this PR.

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Review by gabrieldagama — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B
