### PR TITLE
Replicate old media gallery behavior with current tree path

### LINKED ISSUE #1382: The "catalog/category" and "wysiwyg" directories are not created if Enhanced Media Gallery is enabled
### Preconditions (*)
1. Create a **clean** Magento installation with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Go to _Stores - Configuration - Advanced -System - Enhanced Media Gallery_ and select **Enabled - Yes**
4. Perform ```bin/magento media-gallery:sync``` and ```bin/magento cache:clean```

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Verify that there are no _/wysiwyg_ and _Catalog/category_ Directories
3. Go to **Catalog - Categories**
4. Click **Select from Gallery** button and verify if _Catalog/category_ Directory appeared in folder tree
### Actual result (*)
The _Catalog/category_ Directory did not appear in the folder tree

5. Close Media Gallery
6. Click **Insert/edit image** from Description Editor 
7. Click Search button from **Insert/edit image** window 
8. Verify if _wysiwyg_ Directory appeared in the folder tree
### Actual result (*) 
The _wysiwyg_ Directory did not appear in the folder tree
folder_tree_empty

### Expected result (*)
cat_wys_folders

### Note
- the folders have not been created in _pub/media_
- NOT reproducible with "old" Media Gallery

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1382: The "catalog/category" and "wysiwyg" directories are not created if Enhanced Media Gallery is enabled
2. ...

### Manual testing scenarios (*)
1. Create a **clean** Magento installation with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Go to _Stores - Configuration - Advanced -System - Enhanced Media Gallery_ and select **Enabled - Yes**
4. Perform ```bin/magento media-gallery:sync``` and ```bin/magento cache:clean```

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Verify that there are no _/wysiwyg_ and _Catalog/category_ Directories
3. Go to **Catalog - Categories**
4. Click **Select from Gallery** button and verify if _Catalog/category_ Directory appeared in folder tree

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @Nazar65, thanks for the PR, please follow some considerations below:

I believe the GetTree action should still be just a HttpGetActionInterface, and not implement HttpPostActionInterface. The main objective here is to GetTree and we shouldn't be creating folders, after discussing with @sivaschenko we agreed that a preferred solution would be to:

- Not change the GetTree action and handle the problem on the frontend.
- To avoid overcomplicating the frontend we believe it would be better to handle that on `directoryTree` initialization, by introducing a folder creation request (we already have the endpoint for that) whenever the currentTreePath param exists, if the folder already exists, the request won't do anything and when this request is done we will run `getJsonTree` that will fetch the recently created folder with the tree.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @Nazar65, thanks for the PR, please follow some considerations below:

I believe the GetTree action should still be just a HttpGetActionInterface, and not implement HttpPostActionInterface. The main objective here is to GetTree and we shouldn't be creating folders, after discussing with @sivaschenko we agreed that a preferred solution would be to:

- Not change the GetTree action and handle the problem on the frontend.
- To avoid overcomplicating the frontend we believe it would be better to handle that on `directoryTree` initialization, by introducing a folder creation request (we already have the endpoint for that) whenever the currentTreePath param exists, if the folder already exists, the request won't do anything and when this request is done we will run `getJsonTree` that will fetch the recently created folder with the tree.

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@gabrieldagama could you please review new changes ?

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/web/js/directory/directories.js [hunk 1]
```diff
@@ -56,7 +58,26 @@ define([
                          * Confirm action
                          */
                         confirm: function (folderName) {
-                            this.createFolder(folderName, this.selectedFolder());
+                            var selectedFolder = _.isUndefined(this.selectedFolder()) ||
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/directory/directories.js]: I think we can create a function to return the new folder path, it will be easier to understand than the ternary conditions here.

File: MediaGalleryUi/view/adminhtml/web/js/directory/createDirectory.js [hunk 2]
```diff
@@ -0,0 +1,60 @@
+/**
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
+define([
+    'jquery'
+], function ($) {
+    'use strict';
+
+    return function (createFolderUrl, paths) {
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/directory/createDirectory.js]: I like the approach of isolating these API calls, nice work! I would just put then inside the actions folder.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @Nazar65 thanks for your changes, it looks great! Please follow some thoughts below.

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all test

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento Functional Tests CE

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run Functional Tests B2B,  Functional Tests CE, Functional Tests EE

**Review by sivaschenko — DISMISSED** [review]

**Review by chalov-anton — CHANGES_REQUESTED** [review]
❌ QA Failed

The folder creation and selection is correct. But when the Media Galley Is opened, a _Failed to load resource: the server responded with a status of 400 (Bad Request)_ error message appears in dev console 
400_bad_request

**Comment by sivaschenko** [comment]
@chalov-anton thanks for the verification, please create an issue for this problem for the next milestone

@Nazar65 thanks for the updates, please fix the functional tests

**Comment by chalov-anton** [comment]
> @chalov-anton thanks for the verification, please create an issue for this problem for the next milestone
> 
> @Nazar65 thanks for the updates, please fix the functional tests

:heavy_check_mark: Done

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by gabrieldagama — DISMISSED** [review]

**Comment by chalov-anton** [comment]
✔️ QA Passed
1) If the Enhanced Media Gallery is disabled in _Srores - Configuration_
emg_en_no
It is not available from _Content_
emg_content_no

2) Folder Creation work as expected

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]
