### PR TITLE
#1504: [2.1-develop] Insert rendition images to the content from media gallery instead of original images

### LINKED ISSUE #1504: Insert rendition images to the content from media gallery instead of original images
### Story

https://github.com/magento/adobe-stock-integration/issues/1286

### Precoditions
1. Magento2 2.4-develop with ASI 2.1-develop is installed
2. Enhanced Media Gallery is enabled in `Stores Configuration -> Advanced -> System -> Media Gallery` fieldset
3. Rendition width and height are set in `Stores Configuration -> Advanced -> System -> Media Gallery Renditions` fieldset

### Steps to reproduce:
1. Upload an image that is higher/wider than the configured rendition width/height to the media gallery
2. Insert the image to the content

### Expected result
 - The rendition of the image instead of the original image should be inserted (from `.renditions` directory)
 - The rendition height/width should be reduced not to exceed configured rendition width and height
 - The rendition of the image should keep the original image aspect ratio
 - Used in information should be updated accordingly and displayed in the `Image Details` panel of media gallery

### PR DESCRIPTION
**Pull request by jmonteros422**
Depends on: https://github.com/magento/magento2/pull/29677

### Verify (*)
If approach used is correct.

### Description (*)

This PR implements Insertion of rendition images to the content from media gallery instead of original images. 

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1504: [2.1-develop] Insert rendition images to the content from media gallery instead of original images

### Related Pull Requests
https://github.com/magento/magento2/pull/29677

### Preconditions
1. Magento2 2.4-develop with ASI 2.1-develop is installed
2. Enhanced Media Gallery is enabled in `Stores Configuration -> Advanced -> System -> Media Gallery` fieldset
3. Rendition width and height are set in `Stores Configuration -> Advanced -> System -> Media Gallery Renditions` fieldset

### Steps to reproduce:
1. Upload an image that is higher/wider than the configured rendition width/height to the media gallery
2. Insert the image to the content

### Expected result
 - The rendition of the image instead of the original image should be inserted (from `.renditions` directory)
 - The rendition height/width should be reduced not to exceed configured rendition width and height
 - The rendition of the image should keep the original image aspect ratio
 - Used in information should be updated accordingly and displayed in the `Image Details` panel of media gallery

### CODE REVIEW

**Comment by jmonteros422** [comment]
@magento run all tests

**Comment by jmonteros422** [comment]
@magento run all tests

**Comment by jmonteros422** [comment]
@magento run all tests

**Comment by jmonteros422** [comment]
@magento run static functional tests

**Comment by jmonteros422** [comment]
@magento run all tests

**Comment by jmonteros422** [comment]
@magento run all tests

**Comment by jmonteros422** [comment]
@magento run all tests

File: MediaGalleryRenditions/Plugin/RemovePathOnExtract.php [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+
+    /**
+     * Remove renditions directory from path
+     *
+     * @param ExtractAssetsFromContent $subject
+     * @param string $content
+     * @return array
+     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
+     */
+    public function beforeExecute(ExtractAssetsFromContent $subject, string $content): array
```
Comment (sivaschenko) [inline MediaGalleryRenditions/Plugin/RemovePathOnExtract.php]: Is the correct behavior possible to achieve simply adding the patterns to `media_content.xml` ?

File: MediaGalleryRenditions/etc/module.xml [hunk 2]
```diff
@@ -6,5 +6,11 @@
  */
 -->
 <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
-    <module name="Magento_MediaGalleryRenditions"/>
+    <module name="Magento_MediaGalleryRenditions">
+        <sequence>
```
Comment (sivaschenko) [inline MediaGalleryRenditions/etc/module.xml]: I don't think any updates to sequence are necessary, please update `composer.json` to identify dependencies

File: MediaGalleryRenditions/Plugin/SetPathOnInsert.php [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+
+    /**
+     * Set Rendition's path on content insert
+     *
+     * @param OnInsert $subject
+     * @param callable $proceed
+     * @return ResultInterface
+     * @throws \Magento\Framework\Exception\LocalizedException
+     */
+    public function aroundExecute(OnInsert $subject, callable $proceed): ResultInterface
```
Comment (sivaschenko) [inline MediaGalleryRenditions/Plugin/SetPathOnInsert.php]: I think it might be better to extract the logic from `\Magento\Cms\Controller\Adminhtml\Wysiwyg\Images\OnInsert::execute` to a model (creating a related `magento2` PR) and add a before plugin for that model changing the `filename`.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the PR @jmonteros422 ! Please see my review comments

File: MediaGalleryRenditions/Plugin/RemovePathOnExtract.php (hunk 1 above)
Comment (jmonteros422) [reply MediaGalleryRenditions/Plugin/RemovePathOnExtract.php]: Thanks for the review @sivaschenko!  Will take a check on that one.

File: MediaGalleryRenditions/etc/media_content.xml [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+<!--
+/**
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
+-->
+<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_MediaContentApi:etc/media_content.xsd">
+    <search>
+        <patterns>
+            <pattern name="renditions">/"?.renditions(.*?)"?}}/</pattern>
```
Comment (sivaschenko) [inline MediaGalleryRenditions/etc/media_content.xml]: Please ensure the pattern is covering all the ways the image can be stored in the content.

Here is the current patterns from other modules:

```
            <pattern name="catalog_image">/^\/?media\/(.*)/</pattern>
            <pattern name="catalog_image_with_pub">/^\/pub\/?media\/(.*)/</pattern>
            <pattern name="media_gallery">/{{media url="?(.*?)"?}}/</pattern>
            <pattern name="wysiwyg">/src=".*\/media\/(.*?)"/</pattern>
```

File: MediaGalleryRenditions/Plugin/SetRenditionPath.php [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+        $renditionFilename = $this->getRenditionPath
+            ->execute($this->imagesHelper->idDecode($data['filename']));
+
+        if (!$this->getMediaDirectory()->isFile($renditionFilename)) {
+            return [$data];
+        }
+
+        $data['filename'] = $this->imagesHelper->idEncode($renditionFilename);
+
+        return [$data];
```
Comment (sivaschenko) [inline MediaGalleryRenditions/Plugin/SetRenditionPath.php]: Requires update after https://github.com/magento/magento2/pull/29677 will be updated

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for updates @jmonteros422 ! Looks much better now. Added a couple of comments

**Comment by sivaschenko** [comment]
@magento run all tests

File: MediaGalleryRenditions/Test/Integration/Model/ResourceModel/GetAssetIdsByContentFieldTest.php [hunk 6]
```diff
@@ -0,0 +1,169 @@
...
+
+use Magento\Framework\Exception\InvalidArgumentException;
+use Magento\MediaContentApi\Api\GetAssetIdsByContentFieldInterface;
+use Magento\TestFramework\Helper\Bootstrap;
+use PHPUnit\Framework\TestCase;
+
+/**
+ * GetAssetIdsByContentFieldTest for MediaGalleryRenditions
+ */
+class GetAssetIdsByContentFieldTest extends TestCase
```
Comment (sivaschenko) [inline MediaGalleryRenditions/Test/Integration/Model/ResourceModel/GetAssetIdsByContentFieldTest.php]: Let's avoid using entities fixtures by using the integration test similar to `\Magento\MediaContent\Model\ExtractAssetsFromContentTest` for testing renditions

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for update @jmonteros422 ! Please see my suggestion

**Comment by jmonteros422** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
Should be tested together with https://github.com/magento/magento2/pull/29677

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

Tested together with the dependent M2 PR https://github.com/magento/magento2/pull/29677

The width and heights of the images in the content of Products, Pages... are not bigger than the value set in _Stores - Configuration - System - Media Gallery Renditions_
The images in the content are "taken" from _/pub/medi/.renditions/_ folder
Selection_075
