### PR TITLE
The "See more" button doesn't work when More images are loaded and the same image is previewed again

### LINKED ISSUE #850: The "See more" button doesn't work when More images are loaded and the same image is previewed again
### Preconditions (*)
1. Install Magento with Adobe Stock Integration
2. Configure the integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
### Steps to reproduce (*)
1. From Admin go to **Content** - **Pages**, click **Add New Page**
2. Expand **Content**,click **Show / Hide Editor**, select **Insert Image...**
3. Click **Search Adobe Stock**
4. Click, for example on the first image to open the Preview
5. Click **See more**
see more link
6. From the updated grid, select the same image you've opened previously, and click **See more** 

### Expected result (*)
The page is scrolled to the top

### Actual result (*)
Nothing happens 

see more

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#850: The "See more" button doesn't work when More images are loaded and the same image is previewed again
2. ...

### Manual testing scenarios (*)

1. ...
2. ...

### CODE REVIEW

File: AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ define([
         defaults: {
             template: 'Magento_AdobeStockImageAdminUi/grid/column/preview/related',
             filterChipsProvider: 'componentType = filters, ns = ${ $.ns }',
-            filterTitleSelector: '.admin__current-filters-title-wrap',
+            filterInputSelector: '#words',
```
Comment (VladimirZaets) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js]: Hi, it's not a best practice depends on the element id. In general, it's not the best practice to use id in templates. Current frameworks reuse the template and sometimes we have the cases when template renders on the page a few times, and if we use ID we will get some untraceable issues because due to HTML rule, an ID can be presented only one time on the page.  Please take a is it possible to depend on html class instead of id

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie. Please take a look at my comments below

**Review by sivaschenko — APPROVED** [review]
