### PR TITLE
Fix Could not synchronize assets saved from Adobe Stock

### LINKED ISSUE #1240: Could not synchronize assets saved from Adobe Stock
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. **Have images added to Media Gallery from Adobe Stock**

### Steps to reproduce (*)
From the terminal run ```php bin/magento media-gallery:sync```

### Expected result (*)
Synchronization finished successfully

### Actual result (*) 
sync

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1240: Issue title
2. ...

### Manual testing scenarios (*)
1. Installed Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. **Have images added to Media Gallery from Adobe Stock**

### Steps to reproduce (*)
From the terminal run ```php bin/magento media-gallery:sync```

### Expected result (*)
Synchronization finished successfully

### CODE REVIEW

**Review by sivaschenko — DISMISSED** [review]

File: MediaGallerySynchronization/Model/CreateAssetFromFile.php [hunk 1]
```diff
@@ -30,6 +31,11 @@ class CreateAssetFromFile
      */
     private $driver;
 
+    /**
+     * @var GetByPathInterface
```
Comment (coderimus) [inline MediaGallerySynchronization/Model/CreateAssetFromFile.php]: Please, change the `@var` to `GetAssetsByPathsInterface`

File: MediaGallerySynchronization/Model/CreateAssetFromFile.php [hunk 2]
```diff
@@ -67,9 +76,11 @@ public function execute(\SplFileInfo $file)
         $path = $file->getPath() . '/' . $file->getFileName();
 
         [$width, $height] = getimagesize($path);
+        
 
         return $this->assetFactory->create(
             [
+                'id' => $this->getAssetId($path),
                 'path' => $this->getPath($path),
```
Comment (coderimus) [inline MediaGallerySynchronization/Model/CreateAssetFromFile.php]:
```suggestion
        $path = $file->getPath() . '/' . $file->getFileName();
        $relativePath = $this->getRelativePath($path);
        [$width, $height] = getimagesize($path);

        return $this->assetFactory->create(
            [
                'id' => $this->getAssetId($relativePath),
                'path' => $relativePath,
```

File: MediaGallerySynchronization/Model/CreateAssetFromFile.php [hunk 3]
```diff
@@ -83,6 +94,21 @@ public function execute(\SplFileInfo $file)
...
+     */
+    private function getAssetId(string $path): ?int
+    {
+        $asset = $this->getMediaGalleryAssetByPath->execute([$this->getPath($path)]);
+        if (!empty($asset)) {
+            return $asset[0]->getId();
+        }
+        return null;
+    }
+
```
Comment (coderimus) [inline MediaGallerySynchronization/Model/CreateAssetFromFile.php:107]:
```suggestion
    /**
     * Return asset id if asset already exist by provided path
     *
     * @param string $relativePath
     *
     * @return null|int
     * @throws ValidatorException
     */
    private function getAssetId(string $relativePath): ?int
    {
        $asset = $this->getMediaGalleryAssetByPath->execute([$relativePath]);
        return !empty($asset) ? $asset[0]->getId() : null;
    }
```

Comment (coderimus) [reply MediaGallerySynchronization/Model/CreateAssetFromFile.php:107]: Change `getPath` to `getRelativePath` because this name looks like what is going in the method :)

**Review by coderimus — COMMENTED** [review]
Thank you for your PR @Nazar65 ! It works as expected. I found some cases which we can improve. Please, check my comments below.
cc @sivaschenko

File: MediaGallerySynchronization/Model/CreateAssetFromFile.php (hunk 2 above)
Comment (coderimus) [reply MediaGallerySynchronization/Model/CreateAssetFromFile.php]: If we get $relativePath once at line 84 we would avoid calling it several times for the same result.

File: MediaGallerySynchronization/Model/CreateAssetFromFile.php [hunk 4]
```diff
@@ -70,6 +79,7 @@ public function execute(\SplFileInfo $file)
 
         return $this->assetFactory->create(
             [
+                'id' => $this->getAssetId($path),
                 'path' => $this->getPath($path),
```
Comment (sivaschenko) [inline MediaGallerySynchronization/Model/CreateAssetFromFile.php]: Thanks for suggestion @coderimus 
```suggestion
        $relativePath = $this->getPath($path);

        return $this->assetFactory->create(
            [
                'id' => $this->getAssetId($relativePath),
                'path' => $relativePath,
```

**Comment by coderimus** [comment]
@sivaschenko I see that this PR marked as the 1.1.0  milestone. Should we change its destination branch to 1.1.0-develop then? Or fix can be delivered to the 1.1-develop?

**Review by coderimus — APPROVED** [review]
Hi @Nazar65 ! Thank you for the fix. I made tests and images successfully synchronized. The `media_gallery_asset` d.ata updated.

image

image

NOTE: the last screenshot shows images from the restricted folders such as captcha and . folders. Fix provided for this in the #1236
