### PR TITLE
Correct license image procces to catch errors and show it on media gallery

### LINKED ISSUE #1241: No message is displayed if try to License an image from Standalone Media Gallery with NO secret key
### Preconditions (*)
Magento 2.4-develop
Adobe-Stock-Integration 1.1-develop

1. Installed Magento with Adobe Stock Integration
2. In Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset, set:
- _Enabled Adobe Stock - Yes_
- type a valid _API Key (Client ID)_
- DO NOT enter _Client Secrret_ 
Save Config
3. Save an image preview from Search Adobe Stock

### Steps to reproduce (*)
1. Go to **Content - Media Gallery**
2. Select the previously added Unlicensed Image
3. Click _three dots_ select License

### Expected result (*)
_Login failed. Please check if the Secret Key is set correctly and try again._
secret_key_login failed

### Actual result (*) 
No error message with a link to _Secret key_ configuration
Licensing from standalone with no secret key_2020-04-21

### PR DESCRIPTION
**Pull request by Nazar65**
…lery

### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1241: No message is displayed if try to License an image from Standalone Media Gallery with NO secret key 
2. magento/adobe-stock-integration#1228: Image preview is broken (Licensing)

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery**
2. Select the previously added Unlicensed Image
3. Click _three dots_ select License

### Expected result (*)
_Login failed. Please check if the Secret Key is set correctly and try again._
DeepinScreenshot_select-area_20200421185254

### CODE REVIEW

**Review by lenaorobei — DISMISSED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed
The popup message with the correct link appears

:exclamation: BUT, please consider the following comment to another issue https://github.com/magento/adobe-stock-integration/issues/1228#issuecomment-617701981

File: AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js [hunk 1]
```diff
@@ -101,8 +101,29 @@ define([
                     response.imageDetails.id =  response.imageDetails['adobe_stock'][0].value;
                     response.imageDetails.category =  response.imageDetails['adobe_stock'][3].value;
                     this.image().displayedRecord(response.imageDetails);
-                    this.image().actions().licenseProcess();
-                    this.imageModel().reloadGrid();
+                    $.ajaxSetup({
+                        async: false
```
Comment (sivaschenko) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js]: Is there a case when we can license image or request confirmation asynchronously? If not, I think we can set the corresponding requests to be performed asynchronously rather than changing global setting

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @Nazar65 , can you please take a look at the comment

**Comment by Nazar65** [comment]
@sivaschenko done :heavy_check_mark:

**Comment by sivaschenko** [comment]
Merged to https://github.com/magento/adobe-stock-integration/pull/1275
