### PR TITLE
License an image from the Media Gallery

### LINKED ISSUE #910: License an image from the Media Gallery
### Story

[[Story #39] User license the preview image in Media Gallery](https://github.com/magento/adobe-stock-integration/issues/429)

### Preconditions (*)
1. Install Magento and Adobe Stock Integration [See documentation](https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide)
2. Have a preview image saved from Adobe Stock
3. Have Adobe Stock account with credits - contact @sivaschenko 

### Steps to reproduce (*)
1. Login to Admin panel
2. Open Media Gallery (i.e. Catalog -> Category -> expand Content -> Select from Gallery button)
3. Open the menu for the preview image saved from Adobe Stock

### Expected result (*)
"License" option is present in the image menu. Selecting the option initiates the images licensing process

image

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)

Standalone functionality will work after merge -> https://github.com/magento/adobe-stock-integration/pull/1149/files
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#910: License an image from the Media Gallery
2. ...

 Manual testing scenarios (*)
1. Install Magento and Adobe Stock Integration [See documentation](https://github.com/magento/adobe-stock-integration/wiki/Installation-Guide)
2. Have a preview image saved from Adobe Stock
3. Have Adobe Stock account with credits - contact @sivaschenko 

Steps to reproduce (*)
1. Login to Admin panel
2. Open Media Gallery (i.e. Catalog -> Category -> expand Content -> Select from Gallery button)
3. Open the menu for the preview image saved from Adobe Stock

"License" option is present in the image menu. Selecting the option initiates the images licensing process

### CODE REVIEW

File: AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+    'Magento_Ui/js/modal/alert'
+], function ($, Action, uiAlert) {
+    'use strict';
+
+    return Action.extend({
+        defaults: {
+            template: 'Magento_AdobeStockImageAdminUi/mediaGallery/grid/columns/image/licenseActions',
+            licenseAction: {
+                name: 'license',
+                title: 'License',
```
Comment (VladimirZaets) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js]: Maybe we need to translate the title?

File: AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+                 *
+                 * @param {Object} response
+                 */
+                error: function (response) {
+                    var message;
+
+                    if (typeof response.responseJSON === 'undefined' ||
+                        typeof response.responseJSON.message === 'undefined'
+                    ) {
+                        message = 'There was an error on attempt to get the image details.';
```
Comment (VladimirZaets) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js]: The same here, it should be translated

File: AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+        },
+
+        /**
+         * Check if image licensed
+         *
+         * @param {Object} record
+         * @param {Object} name
+         */
+        isVisible: function (record, name) {
+
```
Comment (VladimirZaets) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js]: Remove empty line

File: AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+            if (name === this.licenseAction.name) {
+                return parseInt(record.licensed, 16) === 0  ? true  : false;
```
Comment (VladimirZaets) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js]: you can just return "parseInt(record.licensed, 16) === 0" it will be boolean automatically

File: AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js [hunk 5]
```diff
@@ -0,0 +1,121 @@
...
+            }
+        },
+
+        /**
+         * Initialize the component
+         *
+         * @returns {Object}
+         */
+        initialize: function () {
+            this._super().observe(['visible']);
```
Comment (VladimirZaets) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js]: Use initObsorvable method to set new observable variables

File: AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+                },
+                context: this,
+
+                /**
+                 * Success handler for deleting image
+                 *
+                 * @param {Object} response
+                 */
+                success: function (response) {
+                    $.ajaxSetup({
```
Comment (VladimirZaets) [inline AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js]: I am not sure that change global ajax configuration is the best solution. I understand that you need to make requests synchronously, but the best solution, in this case, is to make a refactoring of a method that sends requests and gives the ability to receive ajax configuration.

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @Nazar65. Please take a look at my comments below

**Comment by Nazar65** [comment]
Hi @VladimirZaets thank you for review, now it looks much better

**Review by VladimirZaets — APPROVED** [review]
