### PR TITLE
Media gallery synchronization should consider file modification time &&  Performed media gallery && media content synchronization in batches

### LINKED ISSUE #1337: Media gallery synchronization should be performed in batches
Task to address the issue: https://github.com/magento/adobe-stock-integration/issues/1336

### Preconditions (*)
Install Magento 2.4.x with Adobe Stock Integration 2.0.0-develop

### Steps to reproduce (*)
1. Run `bin/magento media-gallery:sync`

### Expected result (*)
Media gallery synchronization should be executed with batch of files rather than for all files at once

### LINKED ISSUE #1338: Media content synchronization should be performed in batches
Task to address the issue: https://github.com/magento/adobe-stock-integration/issues/1336

### Preconditions (*)
Install Magento 2.4.x with Adobe Stock Integration 2.0.0-develop

### Steps to reproduce (*)
1. Run `bin/magento media-conent:sync`

### Expected result (*)
Media content synchronization should be executed with batches of files rather than for all files at once

### LINKED ISSUE #1339: Media gallery synchronization should consider file modification time
Task to address the issue: https://github.com/magento/adobe-stock-integration/issues/1336

### Preconditions (*)
Install Magento 2.4.x with Adobe Stock Integration 2.0.0-develop

### Steps to reproduce (*)
1. Run `bin/magento media-gallery:sync`

### Expected result (*)
Media gallery synchronization should be performed only for files that were modified since the last synchronization execution

### LINKED ISSUE #1340: Media content synchronization should consided entity updated at value
Task to address the issue: https://github.com/magento/adobe-stock-integration/issues/1336

### Preconditions (*)
Install Magento 2.4.x with Adobe Stock Integration 2.0.0-develop

### Steps to reproduce (*)
1. Run `bin/magento media-content:sync`

### Expected result (*)
Media content synchronization should be performed only for entities that were updated since the last synchronization run

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. magento/adobe-stock-integration#1339: Media gallery synchronization should consider file modification time
2. magento/adobe-stock-integration#1337:
Media gallery synchronization should be performed in batches
3.  magento/adobe-stock-integration#1338: Media content synchronization should be performed in batches
4. magento/adobe-stock-integration#1340: Media content synchronization should consided entity updated at value

### Manual testing scenarios (*)
1. Run `bin/magento media-gallery:sync`
2. `php bin/magento media-content:sync`

Media gallery synchronization executed with batch of files 
Verify all files synchronized correctly

Media gallery synchronization should be performed only for files that were modified since the last synchronization execution

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by coderimus — CHANGES_REQUESTED** [review]
Hello @Nazar65 ! Thank you for the provided functionality. Looks great! But there are some failed tests should be checked: Static and Functional - `Creating, deleting new folder functionality in Media Gallery` looks critical. Please, review their reports.

**Comment by coderimus** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by Nazar65** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by coderimus — DISMISSED** [review]
Hi @Nazar65, thank you for the provided changes! Now all tests look great 👍

**Comment by coderimus** [comment]
Hi @sivaschenko, can you please re-checked my review. Everything looks great, but what to be sure that everything right from your side.

File: MediaGallerySynchronization/Model/FetchBatches.php [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+    public function execute(string $tableName, array $columns): \Traversable
+    {
+        try {
+            $connection = $this->resourceConnection->getConnection();
+            $tableName = $this->resourceConnection->getTableName($tableName);
+            $totalPages = $this->getTotalPages($tableName);
+            
+            for ($page = 0; $page < $totalPages; $page++) {
+                $offset = $page * $this->pageSize;
+                $select = $connection->select()
```
Comment (sivaschenko) [inline MediaGallerySynchronization/Model/FetchBatches.php:79]: Can we fetch only entities that are updated after the last synchronization date to avoid the individual checks for each entity?

File: MediaContentSynchronization/Model/IsSynchronizationRequired.php [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+namespace Magento\MediaContentSynchronization\Model;
+
+use Magento\Framework\Stdlib\DateTime\DateTimeFactory;
+use Magento\Framework\FlagManager;
+use Magento\MediaContentSynchronizationApi\Model\IsSynchronizationRequiredInterface;
+
+/**
+ * Verify is synchronization required for entity
+ */
+class IsSynchronizationRequired implements IsSynchronizationRequiredInterface
```
Comment (sivaschenko) [inline MediaContentSynchronization/Model/IsSynchronizationRequired.php]: I don't this this class/interface is necessary

File: MediaGallerySynchronization/Model/GetChangedFiles.php [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+        usort($files, function ($file1, $file2) {
+            $filePath1 = $this->getRelativePath($file1->getPath() . '/' . $file1->getFileName());
+            $filePath2 = $this->getRelativePath($file2->getPath() . '/' . $file2->getFileName());
+            return strcmp($filePath1, $filePath2);
+        });
+        usort($assets, function ($asset1, $asset2) {
+            return strcmp($asset1->getPath(), $asset2->getPath());
+        });
+        
+        return array_udiff_assoc($files, $assets, function ($file, $asset) {
```
Comment (sivaschenko) [inline MediaGallerySynchronization/Model/GetChangedFiles.php]: Does this algorithm work as expected when some of the assets in the database are missing?

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the updates @Nazar65 ! Please see my review comments

File: MediaGallerySynchronization/Model/GetChangedFiles.php (hunk 3 above)
Comment (Nazar65) [reply MediaGallerySynchronization/Model/GetChangedFiles.php]: yes, that files will included

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@sivaschenko done :heavy_check_mark: could you please take a look ?

File: MediaContentSynchronization/Model/Synchronize.php [hunk 4]
```diff
@@ -54,7 +74,9 @@ public function execute(): void
                 $failed[] = $name;
             }
         }
-
+        
+        $this->setLastExecutionTime();
```
Comment (sivaschenko) [inline MediaContentSynchronization/Model/Synchronize.php]: Please move this call to the end of the function to avoid updating the execution time if there were failures

File: MediaGallerySynchronization/Model/SynchronizeFiles.php [hunk 5]
```diff
@@ -73,4 +106,55 @@ public function execute(array $files): void
             );
         }
     }
+
+    /**
+     * Extract path and modification date from File
+     *
+     * @param \SplFileInfo $file
+     */
+    private function extractDataFromFile(\SplFileInfo $file) :array
```
Comment (sivaschenko) [inline MediaGallerySynchronization/Model/SynchronizeFiles.php]: I'd split this method into two separate `getFilePath` and `getModificationTime` methods to avoid complicated array usage

Comment (sivaschenko) [reply MediaGallerySynchronization/Model/SynchronizeFiles.php]: `getFilePath` can also be reused in `getExistingAssets` method

File: MediaContentSynchronizationCms/Model/Synchronizer/Block.php [hunk 6]
```diff
@@ -58,47 +49,60 @@ class Block implements SynchronizerInterface
...
             }
         }
     }
+    
+    /**
+     * Synchronize block entity fields
+     *
+     * @param array $item
+     */
+    private function synchronizeField(array $item): void
```
Comment (sivaschenko) [inline MediaContentSynchronizationCms/Model/Synchronizer/Block.php]: Let's rename this method to `synchronizeItem` or `synchronizeFields`

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the updates @Nazar65 ! Please see my review comments

File: MediaGallerySynchronizationApi/Model/FetchBatchesInterface.php [hunk 7]
```diff
@@ -0,0 +1,26 @@
...
+ * Fetch data from database in batches
+ */
+interface FetchBatchesInterface
+{
+    /**
+     * Fetch the colums from the database table in batches
+     *
+     * @param string $tableName
+     * @param array $columns
+     * @param ?string $modificationDateColumn
```
Comment (gabrieldagama) [inline MediaGallerySynchronizationApi/Model/FetchBatchesInterface.php]:
```suggestion
     * @param string|null $modificationDateColumn
```

File: MediaGallerySynchronizationApi/Model/FetchBatchesInterface.php [hunk 8]
```diff
@@ -0,0 +1,26 @@
...
+
+use Magento\Framework\Exception\LocalizedException;
+
+/**
+ * Fetch data from database in batches
+ */
+interface FetchBatchesInterface
+{
+    /**
+     * Fetch the colums from the database table in batches
```
Comment (gabrieldagama) [inline MediaGallerySynchronizationApi/Model/FetchBatchesInterface.php]:
```suggestion
     * Fetch the columns from the database table in batches
```

**Comment by sivaschenko** [comment]
@magneto run all tests

**Review by sivaschenko — DISMISSED** [review]

**Review by coderimus — DISMISSED** [review]

File: MediaGallerySynchronization/Model/FetchBatches.php [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+                    ->from($this->resourceConnection->getTableName($tableName), $columns)
+                    ->limit($this->pageSize, $offset);
+                !empty($dateColumnName) ?
+                    $select = $this->getLastExecutionCondition($select, $dateColumnName) :
+                    $select;
```
Comment (gabrieldagama) [inline MediaGallerySynchronization/Model/FetchBatches.php]:
```suggestion
                if (!empty($dateColumnName)) {
                    $select = $this->getLastExecutionCondition($select, $dateColumnName);
                }
```

File: MediaGallerySynchronization/Model/FetchBatches.php [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+        }
+    }
+
+    /**
+     * Get where condition if last execution time set
+     *
+     * @param Select $select
+     * @param string $dateColumnName
+     */
+    private function getLastExecutionCondition(Select $select, string $dateColumnName): Select
```
Comment (gabrieldagama) [inline MediaGallerySynchronization/Model/FetchBatches.php]:
```suggestion
    private function addLastExecutionCondition(Select $select, string $dateColumnName): Select
```

File: MediaGallerySynchronization/Model/FetchBatches.php [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+            );
+        }
+    }
+
+    /**
+     * Get where condition if last execution time set
+     *
+     * @param Select $select
+     * @param string $dateColumnName
+     */
```
Comment (gabrieldagama) [inline MediaGallerySynchronization/Model/FetchBatches.php:106]:
```suggestion
     * @return Select
     */
```

File: MediaGallerySynchronization/Model/FetchMediaStorageFileBatches.php [hunk 12]
```diff
@@ -0,0 +1,138 @@
...
+    }
+    
+    /**
+     * Get correct path for media asset
+     *
+     * @param string $file
+     * @return string
+     * @throws ValidatorException
+     */
+    private function getRelativePath(string $file): string
```
Comment (gabrieldagama) [inline MediaGallerySynchronization/Model/FetchMediaStorageFileBatches.php]: This function doesn't seem to be used.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @Nazar65, thanks for the pull request, please follow some small suggestions below:

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Review by coderimus — DISMISSED** [review]

**Review by gabrieldagama — DISMISSED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
http://10.234.235.163:8080/job/Unit-Tests/1642/

**Comment by sivaschenko** [comment]
@magento run Unit Tests

**Review by sivaschenko — APPROVED** [review]
