### PR TITLE
Dynamically create folder by current_tree_path when instance changed

### LINKED ISSUE #1490: "wysiwyg" folder is not created after the "catalog/category" has been created
### Preconditions (*)
1. Installed Magento with Adobe Stock Integration
2. Configured  integration in Stores -> Configuration -> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery enabled

### Steps to reproduce (*)
1. Go to **Content - Media Gallery** and verify that there are no _catalog/category_ and _wysiwyg_ folders. If the folders exist, delete them
2. Go to **Catalog - Categories**
3. Expand **Content**, click **Select from Media Gallery**
4. Verify that the _catalog/category_ folder is created and selected 
cat_cat
5. Close (X) Media Gallery. DO NOT REFRESH the web page
6. Click **Insert/edit image** from **Description** editor
ins_edit
7. Click search source from _Insert/edit image_ window
search_source

### Expected result (*)
_wysiwyg_ folder is created and selected
wys_folder

### Actual result (*)
_wysiwyg_ folder is not created. No folder is selected
cat_cat2

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)

Dynamically create folder by current_tree_path when instance changed

### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1490:"wysiwyg" folder is not created after the "catalog/category" has been created 
2. ...

### Manual testing scenarios (*)
1. Go to **Content - Media Gallery** and verify that there are no _catalog/category_ and _wysiwyg_ folders. If the folders exist, delete them
2. Go to **Catalog - Categories**
3. Expand **Content**, click **Select from Media Gallery**
4. Verify that the _catalog/category_ folder is created and selected 
cat_cat
5. Close (X) Media Gallery. DO NOT REFRESH the web page
6. Click **Insert/edit image** from **Description** editor
ins_edit
7. Click search source from _Insert/edit image_ window
search_source

### Expected result (*)
_wysiwyg_ folder is created and selected
wys_folder

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js [hunk 1]
```diff
@@ -203,21 +210,33 @@ define([
...
-            $(this.directoryTreeSelector).on('loaded.jstree', function () {
-                this.checkChipFiltersState();
-            }.bind(this));
-
             $(window).on('reload.MediaGallery', function () {
-                this.checkChipFiltersState();
+                this.renderDirectoryTree().then(function () {
+                    var path = this.filterChips().get('applied');
+                    this.filterChips().clear();
+                    this.filterChips().set('applied', path);
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: Why do we get the applied filter, clear, and apply the same data again (without changes), is that required here?

**Review by gabrieldagama — COMMENTED** [review]
Hi @Nazar65, thanks for the PR, it looks great! Please follow below a small question, thanks.

File: MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js (hunk 1 above)
Comment (Nazar65) [reply MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: this is like reload event for filters, to avoid double selecting folder in directory tree after reloading

**Comment by Nazar65** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js (hunk 1 above)
Comment (sivaschenko) [reply MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: How "double selecting folder" issue can be reproduced?

Comment (Nazar65) [reply MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: When we reload jstree, selected folder cleared from jstree, and it tries to select directory again for example when we open second time category widget with `current_tree_path="catalog/category"`, and we have already applied directory filter `catalog/category,` then it tries to select `catalog/category `per current_tree_path, but it already applied in filter so second click will remove directory filter. so we also need reload the directory filter when we reload the jstree.

Comment (Nazar65) [reply MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: we also can only call clear() filters, but if we have predefined directory filter in ui bookmarks wich is not catalog/category we need to save this filter and apply after reloading jstree. in another case it will be lost after reload media gallery

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js [hunk 2]
```diff
@@ -203,21 +204,38 @@ define([
...
         initEvents: function () {
+            this.firejsTreeEvents();
             this.overrideMultiselectBehavior();
 
-            $(this.directoryTreeSelector).on('loaded.jstree', function () {
-                this.checkChipFiltersState();
-            }.bind(this));
-
             $(window).on('reload.MediaGallery', function () {
-                this.checkChipFiltersState();
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js:213]: This removal has introduced back the problem when you open the media gallery from the `Select from Gallery` button and the catalog/category folder is selected, but when you go back and open the media gallery from the wysiwyg, the wysiwyg folder is not selected.

File: MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js [hunk 3]
```diff
@@ -295,7 +313,8 @@ define([
          * @param {String} nodePath
          */
         setActiveNodeFilter: function (nodePath) {
-            if (this.activeNode() === nodePath) {
+
+            if (this.activeNode() === nodePath && !this.jsTreeReloaded()) {
```
Comment (gabrieldagama) [inline MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: I would prefer to avoid this approach of using property that can be changed anywhere and change the behaviour of the function, it would be more straight forward to add a parameter to this function that specifically changes its behaviour (would be better to avoid this as well).

From what I could see locally, the problem of opening the gallery multiple times and the folder getting unselected is related to:

```
        /**
         * Locate and higlight node in jstree by path id.
         *
         * @param {String} path
         */
        locateNode: function (path) {
            var selectedId =  $(this.directoryTreeSelector).jstree('get_selected').attr('id');
```

Where the selectedId is undefined and for that reason, it thinks it has to select the folder again.

**Review by gabrieldagama — COMMENTED** [review]
Hi @Nazar65, thanks for your changes, please follow below some considerations.

File: MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js (hunk 3 above)
Comment (Nazar65) [reply MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js]: yes because the jstree reloaded and there is no any selected folder, so in this case we don't need apply filter again as it's already there,A need only select the folder

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

**Comment by Nazar65** [comment]
@magento run all tests
